src/lib.rs
src/volatile.rs
tests/cycles.rs

Detect volatile cycles

---

src/dependencies.rs
src/input.rs
src/lib.rs
src/memoized.rs
src/runtime.rs
src/volatile.rs
tests/incremental/implementation.rs
tests/incremental/main.rs
tests/incremental/memoized_dep_inputs.rs

This is closer to what Glimmer does.

Add support for "dependency only" tracking

---

Cargo.toml

this should go to salsa-rs now

fix repository link

---

src/runtime.rs

closes https://github.com/salsa-rs/salsa/issues/38

impl fmt::Debug for Runtime

---

Cargo.toml
examples/compiler/class_table.rs
examples/compiler/main.rs
examples/hello_world/README.md
src/lib.rs
tests/cycles.rs
tests/incremental/memoized_dep_inputs.rs
tests/incremental/memoized_inputs.rs
tests/incremental/memoized_volatile.rs
tests/set_unchecked.rs
tests/storage_varieties/queries.rs
tests/storage_varieties/tests.rs
tests/variadic.rs

This was driving me crazy.
Fixes #32

Support variadic queries

---

examples/compiler/class_table.rs
examples/hello_world/README.md
src/derived.rs
src/input.rs
src/lib.rs

[WIP] Removal of Eq bound on `Q::Val`

---

src/derived.rs
tests/panic_safely.rs

Panic safely in a single threaded context

---

tests/parallel/cancellation.rs
tests/parallel/setup.rs

Add one more cancellation test

---

Cargo.toml

- Includes GC (#64)
- And a bug fix (#67) for cancellation

release 0.6.2

---

src/derived.rs

My understanding is that `PanicGuard` should be forgotten for every non-panicing execution. 
Let's enforce it with a panic, so that, for example, we won't silently overwrite the keys by adding a `return`.

Panic in PanicGuard if it's not explicitly forgotten

---

Cargo.toml
src/derived.rs
src/input.rs
src/runtime.rs
tests/parallel/main.rs
tests/parallel/stress.rs

@matklad I suspect this fixes your problem, though I've not yet tried to reproduce — we should probably get some sort of test. Still, might be good to verify the hypothesis.
Fixes #70

be more careful when updating after a dependency check

---

Cargo.toml

That is a funny bug!
I was messing up with Cargo recently, and, while compiling rust-analyzer with a locally-build cargo, I've got
```
error[E0514]: found crate `log` compiled by an incompatible version of rustc                                                                                                                              
--> /home/matklad/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.8.0/src/derived.rs:14:5                                                                                                       
|                                                                                                                                                                                                      
14 | use log::{debug, info}; …
```

Don't publish rust toolchain

---

.travis.yml

adjust travis configuration to check we build on stable, test against nightly, etc

build-on-stable etc

---

Cargo.toml

- Includes fix to a subtle cancellation bug (#66)

release 0.9.1

---

components/salsa-macros/src/database_storage.rs
components/salsa-macros/src/query_group.rs
tests/cycles.rs
tests/gc/db.rs
tests/incremental/implementation.rs
tests/parallel/setup.rs
tests/storage_varieties/implementation.rs

This also detected a bunch of crate visibility mismatches in the tests.
cc https://github.com/salsa-rs/salsa/issues/120 -- not a complete fix yet

introduce group storage structs to use from `database_storage` macro

---

Cargo.toml
components/salsa-macros/Cargo.toml

- Make `dyn Trait` implementations work (#133)
Contributors to this release:
- @nikomatsakis

publish v0.10.0-alpha5

---

src/derived.rs

Not sure if we actually should do this, but we can do this, so why not? :)

just clear the table if we are goining to collect everything

---

Cargo.toml
components/salsa-macros/Cargo.toml

Changes:
- Add interned keys to salsa (#150) -- see salsa-rs/salsa-rfcs#2
for more details.
- Fix bugs re: GC and volatile queries
- Optimization for GC (#144), though I think this later got undone
as part of the bug fixes =)

release 0.11.0

---

Cargo.toml
components/salsa-macros/Cargo.toml

- Includes a fix so that interned keys can be send (#155)

release 0.11.1

---

Cargo.toml
components/salsa-macros/Cargo.toml

- Introduce `salsa::transparent` query type(#163)
- Improve salsa proc macro (#160, #162)
- Update parking lot to 0.8.0 (#166)

publish v0.12.1

---

src/derived.rs
tests/panic_safely.rs

Previosly, panicking query would remove in-progress memos from the
table.
However, we use panic for cancellation, so it's reasonable to **not**
remove the old result after panic. This is also known as string
exception safety guarantee: not only database is in *some* consistent
state after a panic, it is in the same state it was before the panic!

implement strong panic safety

---

Cargo.toml

- Don't remove query from storage if its dependency panics (#169)

publish v0.12.2

---

src/runtime.rs

Just a cleanup making use of the new atomic types

switch to AtomicU64

---

Cargo.toml
src/derived.rs
src/lib.rs
src/plumbing.rs
tests/lru.rs

LRU allows to bound the maximum number of *values* that are present in
the table.

Add LRU to derived storage

---

Cargo.toml

- Allow to limit the number of values in a table by using LRU (#171)

publish v0.12.3

---

Cargo.toml
components/salsa-macros/Cargo.toml

Salsa is a team effort, and builds on a mountain of pre-existing
knowledge!
@nikomatsakis wdyt? I personally don't have any strong feelings here :)

Change authors to Salsa developers

---

book/src/common_patterns/on_demand_inputs.md
src/lib.rs

I can squash these commits if that works better.

Fix documentation links + on demand example

---

src/derived/slot.rs

I'm trying to better understand the code and noticed that there are some outdated comments. Let me know if something is inaccurate! (or more places need updating)

Update some comments in slot.rs

---

book/src/common_patterns/on_demand_inputs.md
book/src/common_patterns/selection.md

Found a few more typos in the book.

Fix doc typos

---

FAQ.md

Update New Mexico state question

---

components/salsa-macros/src/query_group.rs

Replaced the panics in the `query_group` macro with `syn::Error`s for better user feedback and experience
Panicking inside of macros doesn't give any locational feedback and can make very annoying-to-debug errors, so this replaces those with returning a `syn` compile error which lets us tag the specific area that's going wrong

Made proc-macros panic less

---

src/lib.rs

Previous output:
```
---- nameres::tests::macros::unexpanded_macro_should_expand_by_fixedpoint_loop stdout ----
thread 'nameres::tests::macros::unexpanded_macro_should_expand_by_fixedpoint_loop' panicked at 'Internal error, cycle detected:
DatabaseKeyIndex { group_index: 2, query_index: 11, key_index: 1 }
', /home/jonas/.cargo/registry/src/github.com-1ecc6299db9ec823/salsa-0.16.1/src/lib.rs:490:48
```
Output after this PR:
```
---- nameres::tests::macros::unexpanded_macro_should_expand_by_fixedpoint_loop stdout ----
thread 'nameres::tests::macros::unexpanded_macro_should_expand_by_fixedpoint_loop' panicked at 'Internal error, cycle detected:
hygiene_frame(HirFileId(MacroFile(MacroFile { macro_call_id: LazyMacro(LazyMacroId(0)) })))
', /home/jonas/dev/salsa/src/lib.rs:492:35
```

Include user-readable query keys in cycle errors

---

book/src/SUMMARY.md
book/src/rfcs/RFC0007-Opinionated-Cancelation.md

@matklad and @jonas-schievink have been discussing a fresh take on salsa that builds on the experience we've gained with it, and one of the first simple steps we wanted to take was to make a more opinionated cancelation model. This is a write-up.

RFC: Opinionated cancelation

---

Cargo.toml
components/salsa-macros/Cargo.toml

Publish 0.17.0-pre.1

---

components/salsa-macros/src/query_group.rs

Now that RA gets to a point where it can expand attributes it would be helpful not to discard parameter names.
Before:
After:

Keep parameter names of queries in `query_group` attribute

---

book/src/SUMMARY.md
book/src/about_salsa.md
book/src/how_salsa_works.md
book/src/videos.md

Add bilibili videos links into book

---

book/src/SUMMARY.md
book/src/rfcs/RFC0007-Opinionated-Cancelation.md
book/src/tuning.md

Document how to tune Salsa
> Re the CI failure: I couldn't repro locally with the same command. On CI, mdbook complains it can't find `./rfcs/RFC0007-Opinionated-cancelation.md`

Document how to tune Salsa

---

components/salsa-entity-macros/src/component.rs

quick fix for components w/ optional jar

---

salsa-2022-tests/tests/expect_reuse_field_x_of_a_tracked_struct_changes_but_fn_deponds_on_field_y.rs
salsa-2022-tests/tests/expect_reuse_field_x_of_an_input_changes_but_fn_deponds_on_field_y.rs

test: expect reuse field X changes but fn depends on field Y

---

components/salsa-2022-macros/src/tracked_fn.rs
salsa-2022-tests/src/lib.rs
salsa-2022-tests/tests/expect_reuse_field_x_of_a_tracked_struct_changes_but_fn_depends_on_field_y.rs
salsa-2022-tests/tests/expect_reuse_field_x_of_an_input_changes_but_fn_depends_on_field_y.rs
salsa-2022-tests/tests/lru.rs

Add method to change LRU capacity at runtime

---

.github/workflows/test.yml
calc-example/calc/src/parser.rs
salsa-2022-tests/tests/accumulate.rs

* run `cargo test -p salsa-2022-tests` in CI
* check format first

run `cargo test -p salsa-2022-tests` in CI

---

calc-example/calc/src/type_check.rs
components/salsa-2022-macros/src/input.rs
components/salsa-2022-macros/src/tracked_fn.rs
components/salsa-2022/src/lib.rs
components/salsa-2022/src/setter.rs
salsa-2022-tests/tests/accumulate-from-tracked-fn.rs
salsa-2022-tests/tests/accumulate-reuse-workaround.rs
salsa-2022-tests/tests/accumulate-reuse.rs
salsa-2022-tests/tests/accumulate.rs
salsa-2022-tests/tests/cycles.rs
salsa-2022-tests/tests/deletion-cascade.rs
salsa-2022-tests/tests/deletion.rs
salsa-2022-tests/tests/expect_reuse_field_x_of_a_tracked_struct_changes_but_fn_depends_on_field_y.rs
salsa-2022-tests/tests/expect_reuse_field_x_of_an_input_changes_but_fn_depends_on_field_y.rs
salsa-2022-tests/tests/hello_world.rs
salsa-2022-tests/tests/mutate_in_place.rs
salsa-2022-tests/tests/override_new_get_set.rs
salsa-2022-tests/tests/specify_tracked_fn_in_rev_1_but_not_2.rs
salsa-2022-tests/tests/tracked_fn_read_own_entity.rs

Implement Setter API

---

salsa-2022-tests/tests/cycles.rs

Add test for durability

---

components/salsa-2022-macros/src/salsa_struct.rs
components/salsa-2022/src/debug.rs

Extract common code that was being repeated for each field of each salsa handled struct to `components/salsa-2022/src/debug.rs` module `helper`.

reduce amount of generated code for `DebugWithDb`

---

README.md
salsa-2022-tests/tests/compile-fail/input_struct_id_fields_no_setters.stderr

cc @zjp-CN 
- Previous link: https://zjp-cn.github.io/salsa
- Fixed link: https://rust-chinese-translation.github.io/salsa-book/

Fix Chinese book link

---

components/salsa-2022/src/interned.rs

In some scenarios the `InternedIngredient` could return two different ids for the same data if called in parallel.

Fix race condition in interned data

---

.github/workflows/test.yml

See https://github.com/salsa-rs/salsa/pull/436#issuecomment-1473737721

Run CI on trybuild test updates

---

Cargo.toml
components/salsa-2022/Cargo.toml

Upgrade to indexmap 2

---

components/salsa-2022/src/tracked_struct.rs
salsa-2022-tests/tests/tracked-struct-unchanged-in-new-rev.rs

update tracked struct `created_at` when validated

---

src/update.rs

I haven't spent much time looking into how all the new Salsa 3.0 stuff works yet, but I think this is correct.

Implement Update for Option<T>

---

components/salsa-macro-rules/src/setup_tracked_fn.rs
components/salsa-macros/src/tracked_fn.rs
tests/tracked_fn_no_eq.rs

Fixes https://github.com/salsa-rs/salsa/issues/521 (at least the `no_eq` part)

Respect `no_eq` attribute for tracked functions

---

.devcontainer/devcontainer.json
.github/dependabot.yml

Basic codespaces config for Rust, created via VSCode's command palette.

basic GitHub codespaces configuration

---

.github/workflows/test.yml
Cargo.toml
benches/incremental.rs

This is @MichaReiser's branch...

Merge Codspeed

---

components/salsa-macro-rules/src/setup_tracked_fn.rs
tests/tracked_fn_constant.rs

Fixes https://github.com/salsa-rs/salsa/issues/565

Fix const queries with custom `Db` trait

---

components/salsa-macros/src/debug.rs
components/salsa-macros/src/tracked_impl.rs
components/salsa-macros/src/xform.rs
tests/tracked_method_with_self_ty.rs

fix: Replace `SelfTy` with actual type in tracked methods

---

src/update.rs

add impl `Update` for `std::convert::Infallible`

---

src/active_query.rs
src/durability.rs
src/input.rs
src/runtime.rs

It is `Option` wrapped in a very few places so might as well

Give Durability niches

---

src/accumulator.rs
src/function.rs
src/ingredient.rs
src/input.rs
src/input/input_field.rs
src/interned.rs
src/key.rs
src/tracked_struct.rs
src/tracked_struct/tracked_field.rs
src/zalsa.rs
src/zalsa_local.rs

Follow up on https://github.com/salsa-rs/salsa/pull/644

Remove panicking paths from `maybe_changed_after`

---

src/function/backdate.rs
src/function/execute.rs
src/function/maybe_changed_after.rs
src/function/memo.rs
src/zalsa_local.rs

* does_what_it_says_on_the_tin.jpg

fix grammar issue in comment

---

benches/accumulator.rs
benches/compare.rs
benches/incremental.rs

I was getting some confusing benchmark results and it looks like some things may be getting optimized out. I added some `black_box` and assert statements to be safer.

`black_box` benchmark inputs and outputs

---

src/zalsa.rs

We hand out mutable references to ingredients nowadays, so we invalidate outstandings refs generally either way

Remove outdated FIXME

---

components/salsa-macro-rules/src/setup_tracked_fn.rs
components/salsa-macros/src/tracked_fn.rs
src/function.rs
src/lib.rs
src/update.rs
tests/compile-fail/tracked_fn_return_not_update.rs
tests/compile-fail/tracked_fn_return_not_update.stderr
tests/compile-fail/tracked_struct_not_update.rs
tests/compile-fail/tracked_struct_not_update.stderr

Closes https://github.com/salsa-rs/salsa/issues/683

Add a compile-fail test for a `'static` `!Update` struct

---

.github/workflows/test.yml

I removed this last week but I think that made codspeed no longer update its baseline

Attempt to fix codspeed

---

components/salsa-macro-rules/src/setup_input_struct.rs
components/salsa-macro-rules/src/setup_interned_struct.rs
components/salsa-macro-rules/src/setup_tracked_fn.rs
components/salsa-macro-rules/src/setup_tracked_struct.rs
components/salsa-macros/src/input.rs
components/salsa-macros/src/interned.rs
components/salsa-macros/src/tracked_struct.rs
src/database.rs
src/function.rs
src/function/memo.rs
src/ingredient.rs
src/input.rs
src/interned.rs
src/lib.rs
src/table/memo.rs
src/tracked_struct.rs
tests/compile-fail/input_struct_incompatibles.rs
tests/compile-fail/input_struct_incompatibles.stderr
tests/compile-fail/interned_struct_incompatibles.rs
tests/compile-fail/interned_struct_incompatibles.stderr
tests/compile-fail/tracked_struct_incompatibles.rs
tests/compile-fail/tracked_struct_incompatibles.stderr
tests/memory-usage.rs

This is https://github.com/salsa-rs/salsa/pull/935 but it incorporates the feedback about the panic handling (https://github.com/salsa-rs/salsa/pull/935#discussion_r2209445203). 
Most of the work in this PR has been done by @ChayimFriedman2

Add heap size support for salsa structs

---

src/table.rs
src/zalsa_local.rs

I believe we don't need the lock as pages are local to a given thread. I also moved the `type_name` field to the vtable, because it's only used in the cold path. I've noticed that any changes to the `Page` can make codspeed angry, so I'll try running the benchmarks on ty as well.

Remove allocation lock

---

src/active_query.rs
src/cycle.rs
src/database.rs
src/durability.rs
src/function.rs
src/function/memo.rs
src/input.rs
src/interned.rs
src/key.rs
src/tracked_struct.rs
src/zalsa.rs
src/zalsa_local.rs
tests/persistence.rs

Various persistent caching bug fixes/improvements. See the individual commits for details.

Persistent caching fixes
