- src/runtime.rs
This public fn dodged the assertion before: https://github.com/nikomatsakis/salsa/blob/e18f14fca5eefc4f104cca85dba3256e6811f9f2/src/lib.rs#L165
> Assert inputs are not modified concurrently

- Cargo.toml
- src/input.rs
- src/lib.rs
- src/memoized.rs
- src/runtime.rs
- tests/set_unchecked.rs
This PR adds a `set_unchecked` method available for input and memoized queries. (I would expect that after https://github.com/salsa-rs/salsa/issues/18 is fixed, it would work for all queries.) It permits one to forcibly **set** a query's value without running the code. This is useful for mocking purposes in writing tests.
> add a `set_unchecked` method that can be used to do mocking in tests

- Cargo.toml
- we now offer a `lock_revision` API, though it is likely to change
- we are now panic safe, but only in a single threaded context
> release 0.6.1

- Cargo.toml
- src/debug.rs
- src/derived.rs
- src/input.rs
- src/lib.rs
- src/plumbing.rs
- src/runtime.rs
- tests/gc/db.rs
- tests/gc/derived_tests.rs
- tests/gc/discard_values.rs
- tests/gc/group.rs
- tests/gc/log.rs
- tests/gc/main.rs
- tests/gc/shallow_constant_tests.rs
- tests/incremental/constants.rs
- tests/incremental/implementation.rs
- tests/incremental/memoized_volatile.rs
This PR adds two methods:
- `db.sweep_all()`, on the database
- `db.query(Foo).sweep()`, on an individual query
These methods will remove all table entries that were not needed in the most recent revision. The intention is that you can do something like this:
```rust
// Start a new revision:
db.salsa_runtime().next_revision();
// Some root query that does everything you need
// e.g., type-checks your program
db.root_query();
// Remove things the root query did not use
db.sweep_all();
```
It also changes how we handle constants. We used to ignore constant inputs **entirely** when doing computation (i.e., we did not record them as inputs). We now distinguish two cases:
- If a derived computation has a mix of constant and non-constant inputs, we will record the inputs faithfully.
- If a …
> introduce garbage collection

- Cargo.toml
Changes:
- correct dead locks and add parallel stress test (#72)
- we now panic if you `get` an input that has not been `set` and
we do not compare inputs for equality (thus dropped `Default` and `Eq`
bounds) (#69)
- more safeguards panic in `PanicGuard` (#71)
> publish v0.7.0

- src/derived.rs
- src/input.rs
- src/lib.rs
- src/plumbing.rs
- src/runtime.rs
- tests/parallel/setup.rs
- tests/parallel/true_parallel.rs
This is an experimental branch.  It introduces a method `salsa_event` into the `Database` trait that defaults to a no-op. This event is given a closure (`event_fn`) which, when called, will produce information about what is happening -- the purpose of the closure is to defer any real work (notably, cloning the descriptor) if the `salsa_event` is not enabled.
This could be used for various purposes. For example, tests can override `salsa_event` and log the events somewhere, using them to reconstruct what happened. I was imagining though that we might provide some higher-level consumers at some point.
This branch uses `salsa_event` in the parallel test to force one thread blocks for another, which we could not do before.
> Simple logging methods

- src/derived.rs
- src/lib.rs
- src/runtime.rs
- tests/panic_safely.rs
- tests/parallel/cancellation.rs
- tests/parallel/fork_from_query.rs
- tests/parallel/frozen.rs
- tests/parallel/independent.rs
- tests/parallel/main.rs
- tests/parallel/race.rs
- tests/parallel/revision_lock.rs
- tests/parallel/setup.rs
- tests/parallel/stress.rs
- tests/parallel/true_parallel.rs
This is the first step towards the "fewer footguns" API.
Opening for discussion.
Some to do items:
> make `fork` give you a `Frozen<DB>`

- examples/hello_world/main.rs
- src/debug.rs
- src/lib.rs
- src/plumbing.rs
- src/runtime.rs
- tests/gc/derived_tests.rs
- tests/incremental/constants.rs
- tests/incremental/memoized_dep_inputs.rs
- tests/incremental/memoized_inputs.rs
- tests/panic_safely.rs
- tests/parallel/cancellation.rs
- tests/parallel/frozen.rs
- tests/parallel/independent.rs
- tests/parallel/race.rs
- tests/parallel/stress.rs
- tests/parallel/true_parallel.rs
- tests/set_unchecked.rs
- tests/variadic.rs
This makes it impossible to try and invoke `set` from a snapshot.
Interestingly, at least the way the library is currently setup, the `&mut` we acquire on the database is only "skin deep" -- this because the `QueryTable` needs to store both a `&Storage` (which is owned by the `db`) and a reference to the db itself. This means that users who "hack up something" against the plumbing APIs directly could -- if they *truly wanted* -- get themselves into deadlocks. I think they have no one to blame but themselves. It might (maybe?) be interesting to think about refactoring things to avoid this, but it doesn't seem very important. I guess the way we would do it using traits so that we only pass down the `&mut DB` but we can extract the storage or other things we need later (vs the current …
> introduce `query_mut` which you must use to get `set` methods

- Cargo.toml
- examples/hello_world/README.md
release 0.8.0
- major refactoring to the database APIs for safer parallel
processing (#78, #82):
- To set an input, you now write `db.query_mut(Query).set(...)`,
and you must declare your database as `mut`.
- To fork a thread, you now write `db.snapshot()`, which acquires
a read-lock that is only released when the snapshot is dropped
(note that this read-lock blocks `set` from occuring on the main
thread).
- Therefore, there can only be one mutable handle to the
database; all other handles are snapshots. This eliminates a variety
of complex and error-prone usage patterns.
- introduced the `salsa_event` callback that can be used for logging
and introspection (#63)
> release 0.8.0

- Cargo.toml
- Panic safety improvements (#81)
- We build on stable now (#94)
- Removed use of dynamic dispatch for constructing query
descriptors (#95)
- Technically a breaking change, though unlikely to affect clients
- Removed use of upgradable reads to avoid Amanieu/parking-lot#101 (#75)
- Upgraded parking lot (#100)
- Improved Debug output (#98)
- Snapshot implements Debug (#85)
> release 0.9.0

- src/derived.rs
- src/runtime.rs
- tests/incremental/memoized_volatile.rs
- tests/parallel/cancellation.rs
- tests/parallel/race.rs
- tests/parallel/setup.rs
An alternate approach to fix #66. The basic problem is that `is_current_revision_canceled` was treated as observing *nothing* when it returned false, but that is only valid if there has never been a value of *true* observed. This PR revises how we track cancellation, which can actually be somewhat simpler since we no longer have multiple active writers to the database. We now track the revisions where cancellation occurs -- so, if revision R2 was canceled, then when you get back `false` from `is_current_revision_canceled`, that is treated as a read from R3.
Essentially, the 'next uncanceled revision' acts like an ordinary input -- it records the last time it was changed, and when you read from it, you see the corresponding dependency. There are however two differences between this and an …
> Issue 66 transitive cancelation

- src/derived.rs
- src/input.rs
- src/lib.rs
- src/runtime.rs
- tests/panic_safely.rs
- tests/parallel/cancellation.rs
- tests/parallel/setup.rs
This adds unwinding based cancellation (user is responsible for both panicking and catching). The current `anon_read` infrastructure is not deleted yet. We probably should tear it down though?
Tests are rewritten to use panics, except for the one which does not make sense with panicking. This test still uses the old-style cancelation.
Future work:
* either remove anon-read, or make sure we test both anon-reads and unwinding
* improve PanicGuard such that it restores old value, thus achieving strong exception safety guarantee.
> Unwinding-based cancelation via panic hook

- Cargo.toml
- Introduces the `propagated_panic` hook and specify that the
salsa storage types are unwind safe (#107).
> release 0.9.2

- components/salsa_macros/src/lib.rs
- src/lib.rs
Instead of generating
```rust
trait Query: GetQueryTable<Foo> {
fn foo() { .. }
}
```
generate
```rust
trait Query {
}
impl<T> Query for T
where
T: GetQueryTable<Foo>,
{
fn foo() { .. }
}
```
> generate an impl of the trait from procedural macro

- Cargo.toml
- components/salsa-macros/Cargo.toml
The big change here is that we have started work on implementing https://github.com/salsa-rs/salsa-rfcs/pull/1. You now create query groups by making a trait:
```
#[salsa::query_group]
trait MyQueryGroup {
fn my_query(&self, key: K) -> V;
}
```
See the `salsa::query_group` procedural macro for more information.
> release 0.10.0-alpha1

- src/runtime.rs
- src/runtime/local_state.rs
- tests/panic_safely.rs
Previously, the local query stack was not recovered if there was a panic. Fix that.
cc @kleimkuhler
> Clear query stack on panic

- src/runtime.rs
- src/runtime/local_state.rs
in general, the more narrowly we can make the claim, the easier it is to verify
> move the RefUnwindSafe impls to shared/local state structs

- components/salsa-macros/Cargo.toml
- components/salsa-macros/src/database_storage.rs
- components/salsa-macros/src/lib.rs
- components/salsa-macros/src/query_group.rs
- examples/compiler/implementation.rs
- examples/hello_world/README.md
- examples/hello_world/main.rs
- src/derived.rs
- src/input.rs
- src/lib.rs
- src/plumbing.rs
- src/runtime.rs
- src/runtime/local_state.rs
- tests/cycles.rs
- tests/gc/db.rs
- tests/incremental/implementation.rs
- tests/panic_safely.rs
- tests/parallel/setup.rs
- tests/parallel/stress.rs
- tests/set_unchecked.rs
- tests/storage_varieties/implementation.rs
- tests/variadic.rs
By the end of this PR, the `database_storage` macro format just lists out the query group *traits*, not the queries within:
```rust
salsa::database_storage! {
pub MyDatabaseStruct {
impl MyQueryGroup;
}
}
```
I would like to move to a `#[salsa::database(...)]` annotation on the struct itself but that is left for a future PR. =) (Other bits of future work include generating the `set_foo` methods and so forth and (hopefully) removing the `query` and `query_mut` methods in the `Database` trait).
I had to do things just a *hair* differently than anticipated, so I need to update the RFC. The salsa `Query` trait grew "group storage" and "group descriptor" associated types and so forth. I think that trait really ought to wind up in `plumbing`.
cc #120
> remove the need to list individual queries in group storage struct

- components/salsa-macros/src/database_storage.rs
- components/salsa-macros/src/lib.rs
- examples/compiler/implementation.rs
- examples/hello_world/main.rs
- tests/cycles.rs
- tests/gc/db.rs
- tests/incremental/implementation.rs
- tests/panic_safely.rs
- tests/parallel/setup.rs
- tests/parallel/stress.rs
- tests/set_unchecked.rs
- tests/storage_varieties/implementation.rs
- tests/variadic.rs
With this change, you write
```rust
#[salsa::database(QueryGroup1, QueryGroup2)]
struct MyDatabase { .. }
```
instead of `salsa::database_storage! { ... }`.
cc https://github.com/salsa-rs/salsa/issues/120
> adopt `salsa::database` attribute macro

- src/debug.rs
- src/derived.rs
- src/input.rs
- src/plumbing.rs
- tests/gc/derived_tests.rs
- tests/gc/discard_values.rs
- tests/gc/main.rs
- tests/gc/shallow_constant_tests.rs
I'd love to answer the question "how much syntax trees are retained in the salsa database", and for that, peeking at values seems useful.
> allow to peek at values via debug query interface

- Cargo.toml
- You now write `#[salsa::database(query_groups...)]` instead of
`database_storage!`, and you don't ned to list individual
queries (#123, #124, #125)
- We now generate `set_foo` methods for inputs (#126)
- We can now peek at values using debug query interface (#122)
- Local handles recover from unwinds better (#114)
- We don't issue docs for `__SalsaQueryDescriptor` (#116)
- The unwind safety impls were moved about (internal refactoring, #115)
Contributors (since I've not been citing these in the past, this
includes all contributors to salsa to date):
- @cormacrelf
- @fabianschuiki
- @jrmuizel
- @kleimkuhler
- @matklad
- @memoryruins
- @nikomatsakis
> release 0.10.0-alpha2

- components/salsa-macros/src/database_storage.rs
- components/salsa-macros/src/query_group.rs
- examples/compiler/class_table.rs
- examples/compiler/implementation.rs
- examples/hello_world/main.rs
- src/lib.rs
- src/plumbing.rs
- tests/cycles.rs
- tests/gc/db.rs
- tests/gc/group.rs
- tests/incremental/constants.rs
- tests/incremental/implementation.rs
- tests/incremental/memoized_dep_inputs.rs
- tests/incremental/memoized_inputs.rs
- tests/incremental/memoized_volatile.rs
- tests/macros.rs
- tests/panic_safely.rs
- tests/parallel/setup.rs
- tests/parallel/stress.rs
- tests/set_unchecked.rs
- tests/storage_varieties/implementation.rs
- tests/storage_varieties/queries.rs
- tests/variadic.rs
As @matklad noted, having the `#[salsa::database]` macro find the associated group storage / group key structs by manipulating the path proved to be too fragile, thus making the salsa abstraction more leaky than we might like. To fix this, we introduce the idea of a **query group struct** -- this struct now defines the query group, rather than the trait. You specify the struct name in the `#[salsa::query_group]` attribute macro:
```rust
#[salsa::query_group(MyQueryGroup)]
trait MyQueryGroupDatabase {
...
}
```
As you can see, by convention the name of the struct is the name of the query group (`MyQueryGroup`) and the trait has the word `Database` attached to it (i.e., it is implemented by the database which supports this query group).
Now, the `#[salsa::database]` struct refers to the …
> Introduce "query group struct"

- components/salsa-macros/src/query_group.rs
All the example code uses Default to create the db structs, but it turns
out the *GroupStorage's `#[derive(Default)]` adds a trait bound of
(e.g.) `DB__: Default + HelloWorldDatabase` even though it never
actually needs to call HelloWorldDatabase::default(). So if you didn't
implement Default, you couldn't be a salsa database struct.
Not implementing default is pretty useful for a generic db struct.
> Manually implement Default for *GroupStorage

- Cargo.toml
- components/salsa-macros/Cargo.toml
- Introduce requirement for group storage structs (#130)
- Manually implement Default (#131)
Contributors to this release:
- @cormacrelf
- @nikomatsakis
> Release salsa-0.10.0-alpha4

- components/salsa-macros/src/query_group.rs
Not sure why this isn't signaling warnings all over the place, but I see them in other projects.
> apply `non_camel_case_types` to the enum variant

- src/derived.rs
- src/input.rs
- src/lib.rs
- src/plumbing.rs
Follow-up of #140. Removes the trait from plumbing and the implementations.
> remove `UncheckedMutQueryStorageOps` trait

- tests/gc/derived_tests.rs
- tests/incremental/memoized_dep_inputs.rs
- tests/incremental/memoized_inputs.rs
- tests/panic_safely.rs
- tests/parallel/cancellation.rs
- tests/parallel/frozen.rs
- tests/parallel/independent.rs
- tests/parallel/race.rs
- tests/parallel/stress.rs
- tests/parallel/true_parallel.rs
- tests/variadic.rs
Closes #128
Converts tests to use `set_foo` now that set methods are generated for inputs.
> convert tests to use generated set methods

- src/derived.rs
- src/lib.rs
- tests/gc/derived_tests.rs
- tests/gc/discard_values.rs
- tests/gc/shallow_constant_tests.rs
- tests/parallel/stress.rs
This tweaks curreng GC API to make it more flexible and (subjectively) clearer. 
Now, the effect of GC is a "product" of three parameters:
* what values are affected (everything/everything except used)
* are we removing values
* are we removing deps
SweepStrategy::default is a no-op GC, each method allows one to gc *more*.
The strategy I think I need for rust-analyzer is "drop all values from all revisions, but keep all dependencies". I use it like this:
https://github.com/rust-analyzer/rust-analyzer/blob/ca382ba18bdb55ed0c7b5ea3eb1eb30e8cd636ce/crates/ra_ide_api/src/imp.rs#L80-L112
> Make GC API more orthogonal and flexible

- Cargo.toml
- components/salsa-macros/Cargo.toml
- GC API now more orthogonal + flexible (#138)
- Removed `set_unchecked` testing mechanism (#141)
- Generated enums now squelch `non_camel_case_types` lint (#135)
- Tests now using `set_foo` (#139)
- `Query::group_storage` now called `Query::query_storage` (#142)
Contributors to this release:
- @matklad
- @memoryruins
- @nikomatsakis
> release 0.10.0

- components/salsa-macros/Cargo.toml
- components/salsa-macros/src/query_group.rs
- src/derived.rs
- src/interned.rs
- src/lib.rs
- src/plumbing.rs
- tests/gc/db.rs
- tests/gc/interned.rs
- tests/gc/main.rs
- tests/gc/volatile_tests.rs
- tests/interned.rs
This is a WIP PR. It adds a new kind of salsa key, `#[salsa::interned]`. This uses an internal storage that maps key values to an integral value. So the query might look like:
```rust
#[salsa::interned]
fn intern1(&self, x: String) -> u32;
```
For every interned key, there will automatically be a `lookup_intern1` method added as well. Also, the return type does not have to be `u32`, it can be any newtype of `u32` so long as it implements the `salsa::InternKey` trait. So you can do something like this:
```rust
#[salsa::interned]
fn intern_key(&self, x: String) -> InternKeyType;
```
where `InternKeyType` implements `salsa::InternKey`. The `InternKey` trait is very simple:
```rust
/// Trait implemented for the "key" that results from a
/// `#[salsa::intern]` query.  This is basically meant …
```
> add interned keys to salsa

- src/lib.rs
- src/plumbing.rs
- tests/no_send_sync.rs
This removes the last remaining uses of `: Send + Sync`, fixing https://github.com/salsa-rs/salsa/issues/152.
> Removed remaining stray bounds for `Send + Sync` that still survived PR #42 

- src/interned.rs
- src/lib.rs
- src/raw_id.rs
- tests/gc/interned.rs
- tests/interned.rs
Per @matklad's suggestion, create a `RawId` type and use it in place of `u32` for interned keys.
> adopt raw-id for interned keys

- Cargo.toml
- components/salsa-macros/Cargo.toml
- Introduce `InternId` as the basis for interned keys, replacing
`u32` (#157, #158)
- Support keys/values that are not `Send/Sync` (#153)
> publish v0.12.0

- components/salsa-macros/src/query_group.rs
This is just a silly detail but I noticed that the auto-generated documentation for `salsa::query_group` does not interpolate the method names correctly. It's a bit unfortunate to deal with string formatting though :disappointed: 
I could generate a more precise markdown link to `fn_name` but I feel it'd a bit fragile?
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
> Improve doc comments generation

- components/salsa-macros/src/query_group.rs
Closes #161
I am not sure if this is entirely correct only because the code doesn't "read right" to me.
If the `SelfRef`'s `mutability` is `None` (so it is `&self`, I _assume_) panic saying you must use `&self`.
Is this correct?
> Remove mention of unsupported '&mut self' in a query group panic

- components/salsa-macros/src/query_group.rs
- tests/transparent.rs
Transparent queries are not really queries: they are just plain
uncached functions without any backing storage.
Making a query transparent can be useful to figure out if caching it
at all is a win.
Context:
I need this in rust-analyzer. I want to change the input to the system from files with `String` contents to a roughly pair of `(String, Mutex<Option<CachedSyntaxTree>>)`, such that I can implement LRU eviction of syntax trees outside of salsa. Currently `parse(FIleId) -> SyntaxTree` is a query, and I'd love to preserve this API. However, if `parse` will be caching trees in any way, that would completely undo any eviction I implement :-)
> Add transparent query type

- Cargo.toml
- components/salsa-macros/src/database_storage.rs
- components/salsa-macros/src/query_group.rs
- src/debug.rs
- src/dependency.rs
- src/derived.rs
- src/derived/slot.rs
- src/doctest.rs
- src/input.rs
- src/interned.rs
- src/lib.rs
- src/lru.rs
- src/lru/test.rs
- src/plumbing.rs
- src/runtime.rs
- src/runtime/local_state.rs
As discussed on Zulip this PR series optimizes our internal dependency data structures to avoid hashing of keys/values on query revalidation. My measurements found this to be approximately a ~35% win, though @matklad saw results up to 50%. 
This PR *does* introduce some subtle logic around Send+Sync owing to the use of trait objects. It requires a bit of a hack to ensure that the database is Send+Sync iff the keys/values are Send+Sync. I found what feels like a decent solution to this problem by transmuting a `Arc<dyn Slot>` to a `Arc<dyn Slot + Send + Sync>` and using phantom-data to ensure that the composite is only send+sync if the keys/values are send+sync. The truth is that this is kind of overkill since slots are not exposed outside of the database, and if the keys/values are not …
> introduce slots

- src/dependency.rs
no strong opinion here, but seems just a hair slightly more direct than exposing `*const`
> use ptr::eq/hash for readability

- src/runtime.rs
We don't use `RuntimeId` to index memory, so using usize is
not the best fit semantically
> use AtomicU64 for RuntimeId

- RELEASES.md
Published: 2019.08.15
- adopt the new `Durability` API proposed in [RFC #6]
- this replaces and generalizes the existing concepts of constants
- remove "volatile" queries -- instead, you can use
`report_untracked_read` method on the salsa runtime
- introduce "slots", an optimization to salsa's internal workings
- document `#[salsa::requires]` attribute, which permits private dependencies
- Adopt `AtomicU64` for `runtimeId` (#182)
- use `ptr::eq` and `ptr::hash` for readability
- upgrade parking lot, rand dependencies
[RFC #6]: https://github.com/salsa-rs/salsa-rfcs/pull/6
> publish 0.13.0

- components/salsa-macros/src/query_group.rs
- src/derived.rs
- src/derived/slot.rs
- src/doctest.rs
- src/input.rs
- src/interned.rs
- src/lib.rs
- src/plumbing.rs
- src/runtime.rs
- src/runtime/local_state.rs
- tests/cycles.rs
- tests/parallel/cancellation.rs
- tests/parallel/independent.rs
- tests/requires.rs
- tests/transparent.rs
The default behavior when salsa detects a cycle is to panic. This is fine behavior when the cycle occurs as a programmer error but in some instances cycles can be expected to occur. To allow this case while still keeping "programmer error" as the default assumption on cycles a `salsa::cycle` is added which can be attached to any function which could naturally appear in a cycle.
The `salsa::cycle` takes a function which takes the keys of the query as well as description of all the queries that were part of the cycle (currently a slice of `Debug` formatted strings for simplicity's sake). When a cycle is detected salsa invokes the cycle function to produce the result for the query instead of panicking. Furthermore, every other query in the cycle will discard whatever value they produced …
> feat: Allow queries to avoid panics on cycles

- components/salsa-macros/src/query_group.rs
- examples/compiler/implementation.rs
- examples/hello_world/main.rs
- src/derived.rs
- src/doctest.rs
- src/input.rs
- src/lib.rs
- src/plumbing.rs
- src/runtime.rs
- tests/cycles.rs
- tests/dyn_trait.rs
- tests/gc/db.rs
- tests/gc/derived_tests.rs
- tests/gc/discard_values.rs
- tests/gc/interned.rs
- tests/gc/shallow_constant_tests.rs
- tests/incremental/implementation.rs
- tests/incremental/memoized_volatile.rs
- tests/interned.rs
- tests/lru.rs
- tests/no_send_sync.rs
- tests/on_demand_inputs.rs
- tests/panic_safely.rs
- tests/parallel/setup.rs
- tests/parallel/stress.rs
- tests/requires.rs
- tests/storage_varieties/implementation.rs
- tests/storage_varieties/tests.rs
- tests/transparent.rs
- tests/variadic.rs
We always *intended* that to create a new revision you needed `&mut self`, but this was enforced not by the `SalsaRuntime` itself but by the DB. The reason for this was primarily that we needed to have (a) a reference to the DB that overlapped with (b) a reference to query tables owned by the database, and that didn't permit `&mut`. But if we move those query tables into an `Arc`, we can resolve this problem, and then we can have `with_incremented_revision` take `&mut self` (which is what this PR does).
This would be largely unobservable to users, except that it it fixes an existing hole in the API and hence is a breaking change (it also requires a new `salsa_runtime_mut` method). The hole is that before you could invoke `synthetic_write` with only an `&DB`, which means you could do it …
> require `&mut self` for moving to a new revision (breaking)

- .travis.yml
`mdbook` generate two directories: `html` with rendered book and `linkcheck` with output of `mdbook-linkcheck`. Set deploy only `html` dir.
> Fix deploy book

- Cargo.toml
- src/lib.rs
While `derive-new` isn't on the critical path, it still takes some 6 seconds to compile on a reasonably fast laptop, and the freed up CPU can be used for something else:
Perhaps it's worth writing a couple of lines of code by hand.
> Implement QueryTable constructor manually instead of using derive-new

- book/src/plumbing.md
Fixed a small typo in `plumbing.md`.
> Fix a typo in book

- .github/workflows/test.yml
- Cargo.toml
- src/interned.rs
Only AtomicCell is used from crossbeam and SmallRng from rand so we can
easily disable the default features
> feat: Prune unnecessary dependencies

- src/blocking_future.rs
- src/derived/slot.rs
- src/lib.rs
cargo llvm-lines shows that some amount of llvm lines is spend on
`std::mpsc`. Given that this is not the most loved standard library
module, and that our usage of mpsc is extremely limited, it seems
worth-while to implement oneshot channel using parking_lot.
I was going to submit an issue about how we should do this, but then accidentally just impled the thing :D
> Replace usage of `std::mpsc` with something more light-weight

- src/revision.rs
- src/runtime.rs
rust-analyzer fails in rust-lang/rust repo on the power target,
because it doesn't have `AtomicU64`. So, lets just use `AtomicUsize`
as a revision number.
Semantically this is wrong, as we are not using revision to address
arrays, but, practically, it's a nice compromise to build on targets
without AtomicU64 and to have large revision numbers on most relevant
targets.
> Make salsa buildable on power

- src/derived/slot.rs
`FxIndexSet` has considerable overhead and is only iterated over once it's in the `Slot`. Use a boxed slice instead, saving 300-400 MB of memory in a rust-analyzer benchmark.
> Use a boxed slice to store dependencies

- src/derived.rs
- src/input.rs
- src/interned.rs
- src/lib.rs
- src/lru.rs
- src/plumbing.rs
This is mostly useful for debugging, rust-analyzer uses it to measure
memory usage of tables
> Add purge method

- src/derived/slot.rs
- src/runtime.rs
This makes it possible to debug unwanted query dependencies by looking at the log output.
Previous output:
```
[2021-05-05T13:15:48Z DEBUG salsa::derived::slot] read_upgrade(FileItemTreeQuery(HirFileId(FileId(FileId(0))))): result.changed_at=R6, result.durability=Durability(0), result.dependencies = Some(
{
DatabaseKeyIndex {
group_index: 1,
query_index: 0,
key_index: 0,
},
DatabaseKeyIndex {
group_index: 2,
query_index: 0,
key_index: 0,
},
},
)
[2021-05-05T13:15:48Z DEBUG salsa::derived::slot] read_upgrade(FileItemTreeQuery(HirFileId(FileId(FileId(0))))): inputs=Tracked { inputs: [DatabaseKeyIndex { group_index: 1, query_index: 0, key_index: 0 }, DatabaseKeyIndex { group_index: 2, query_index: 0, key_index: 0 }] }
```
New output:
```
[2021-05-05T13:31:26Z DEBUG salsa::derived::slot] …
```
> Log `MemoInputs` in human-readable form

- book/src/common_patterns/on_demand_inputs.md
The query in the on demand input example in the book seems out of date since at least https://github.com/salsa-rs/salsa/commit/9b9dbcca8c8e12b24b7c25470af9e070684821e1#diff-c86c61ef2a1841ef63294b8494f6a783
I also have a more complete example of integrating with notify [in this git repo](https://github.com/ChristopherBiscardi/salsa-file-watch-example/blob/f968dc8ea13a90373f91d962f173de3fe6ae24cd/main.rs) with a [writeup](https://www.christopherbiscardi.com/on-demand-lazy-inputs-for-incremental-computation-in-salsa-with-file-watching-powered-by-notify-in-rust) to go with it. I'm happy to put that code and such in this file if you think that would be better.
> update on_demand_inputs invalidation

- examples/compiler/compiler.rs
Makes the compiler example read better.
> remove some unneeded lifetime parameters

- .github/workflows/book.yml
Removes the [deprecated](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) `add-path` command and bumps the versions.
> Fix book workflow

- src/lib.rs
Improve visibility by placing the `database` and `query_group` proc macros at the bottom of the main docs page, instead of manually browsing to the docs for the `salsa-macros` crate.
> Expose proc macro docs via the main crate

- .github/workflows/test.yml
Only the stable toolchain appears to install `rustfmt` by default
> CI installs `rustfmt` where needed

- components/salsa-macros/src/query_group.rs
This was added in https://github.com/salsa-rs/salsa/commit/fd036a4f154c46253443b3a79b6f4400c40e87b1, but never actually came into effect.
Granting access to `QueryTableMut` for every query type should be harmless, because every method on that type has a where-clause that makes it only work with the right query storage type.
> Remove dead code

- src/derived.rs
- src/derived/slot.rs
- src/runtime.rs
- src/runtime/local_state.rs
- tests/on_demand_inputs.rs
Fixes https://github.com/salsa-rs/salsa/issues/246
Fixes https://github.com/salsa-rs/salsa/issues/277
`report_synthetic_read` only forced the durability of the current query to some lower value, but didn't set its `changed_at` value, leading to downstream queries assuming that they could reuse the query's value when they could not. Force `changed_at` to the current revision to fix that. This will not result in unnecessary invocations of the query, because salsa still treats it as pure, and won't re-run it if its inputs are up to date.
Additionally, `invalidate` did also not set the slot's `changed_at` field, which is fixed by setting it to the newly created revision.
> Fix `invalidate` and `report_synthetic_read`

- .github/workflows/book.yml
- book/book.toml
- bors.toml
I noticed the book workflow [failing](https://github.com/salsa-rs/salsa/runs/3568827495?check_suite_focus=true) on master. This PR attempts to fix the failing workflow and prevent failing book deploys in the future.
- Add the book build to `bors.toml`.
- Make sure the book workflow runs for the bors branches (`staging` and `trying`).
- Exclude the bilibili domain in the mdbook-linkcheck config to prevent the 403s.
I also bumped mdbook and mdbook-mermaid versions.
> Update book workflow

- Cargo.toml
crossbeam_utils is currently not used anywhere withing this crate so I propose to remove the dependency to (slightly) reduce compile times
> Remove unused crossbeam_utils dependency

- src/derived.rs
- src/input.rs
- src/runtime.rs
Removes a bug vector, since this function would
panic if the closure is used more than once.
iuc, the code opted out of the compiler's checks
before via a clever `.take()`.
Another change is to take the closure by value
rather than by reference. The monomorphization
seems harmless, since `with_incremented_revision`
is only called from two places.
> Make with_incremented_revision take FnOnce

- examples/compiler/interner.rs
- examples/hello_world/main.rs
Two examples had a superfluous bound
': salsa::Database' that wasn't present
in the `compiler` example and doesn't seem to be needed.
The `query_group` macro adds this bound
automatically.
This change can lead to a trailing `+` in
the bounds list. I verified this is OK by
running the examples and verifying that the production
is allowed
[per the Rust Reference](https://doc.rust-lang.org/reference/trait-bounds.html)
> Remove ': salsa::Database' bound from two examples

- components/salsa-macros/src/query_group.rs
Update the macro for `query_group` so the comment
on `fn in_db` no longer says that it is more common
to use the trait method on `db`.
Afaict, the trait methods referred to were removed
when dyn database were introduced in RFC0006:
./book/src/rfcs/RFC0006-Dynamic-Databases.md, as
described in the section
"Instead of `db.query(Q)`, you write `Q.in_db(&db)`"
> Update doc in macro about query.in_db for dyn db

- components/salsa-macros/src/query_group.rs
This change resolves a fixme that referenced #120.
This change breaks no tests, and, if I understand
correctly, does not affect user-facing API.
Here is the difference for the `HelloWorldGroupStorage__` struct
generated from macros in the `hello_world` example:
**Before:**
```rs
struct HelloWorldGroupStorage__ {
pub input_string:std::sync::Arc<<InputStringQuery as salsa::Query> ::Storage> ,pub length:std::sync::Arc<<LengthQuery as salsa::Query> ::Storage> ,
}
```
**After:**
```rs
struct HelloWorldGroupStorage__ {
input_string:std::sync::Arc<<InputStringQuery as salsa::Query> ::Storage> ,length:std::sync::Arc<<LengthQuery as salsa::Query> ::Storage> ,
}
```
> Make storage fields of #nameGroupStorage private

- book/src/cycles.md
In cycle.md, change `[salsa::Cycle]` to `salsa::Cycle` so mdbook doesn't get confused
and think there is a broken Markdown link ("warning: Potential incomplete link").
After fixing this problem, there are no more mdbook warnings when
running `mdbook build` in the "book" directory.
> Fix mdbook warning re "Potential incomplete link"

- components/salsa-2022-macros/src/accumulator.rs
- components/salsa-2022-macros/src/jar.rs
- components/salsa-2022-macros/src/options.rs
- components/salsa-2022-macros/src/salsa_struct.rs
- components/salsa-2022-macros/src/tracked_fn.rs
- salsa-2022-tests/Cargo.toml
- salsa-2022-tests/tests/cycles.rs
- salsa-2022-tests/tests/parallel/main.rs
- salsa-2022-tests/tests/parallel/parallel_cycle_all_recover.rs
- salsa-2022-tests/tests/parallel/parallel_cycle_mid_recover.rs
- salsa-2022-tests/tests/parallel/parallel_cycle_none_recover.rs
- salsa-2022-tests/tests/parallel/parallel_cycle_one_recover.rs
- salsa-2022-tests/tests/parallel/setup.rs
- salsa-2022-tests/tests/parallel/signal.rs
closes #331 
This pr ports the old salsa tests for cycle in a single thread, except for [cycle_disappears_durability](https://github.com/salsa-rs/salsa/blob/03a27a7054ee234a566231243dd5025edfbcdde6/tests/cycles.rs#L326), since we don't have the api that permits setting durability.  
~I haven't ported parallel related tests, which would be some work, wondering if we can merge this in first~
> Add options to tracked functions for cycle recovery

- components/salsa-2022-macros/src/db.rs
- components/salsa-2022/src/accumulator.rs
- components/salsa-2022/src/event.rs
- components/salsa-2022/src/function.rs
- components/salsa-2022/src/function/diff_outputs.rs
- components/salsa-2022/src/function/specify.rs
- components/salsa-2022/src/ingredient.rs
- components/salsa-2022/src/input.rs
- components/salsa-2022/src/input_field.rs
- components/salsa-2022/src/interned.rs
- components/salsa-2022/src/runtime.rs
- components/salsa-2022/src/runtime/active_query.rs
- components/salsa-2022/src/runtime/local_state.rs
- components/salsa-2022/src/storage.rs
- components/salsa-2022/src/tracked_struct.rs
- salsa-2022-tests/tests/accumulate-and-reuse.rs
- salsa-2022-tests/tests/accumulate-from-tracked-fn.rs
- salsa-2022-tests/tests/accumulate-reuse-workaround.rs
- salsa-2022-tests/tests/accumulate-reuse.rs
- salsa-2022-tests/tests/accumulate.rs
This branch fixes accumulators so they have the right *behavior* -- the implementation leaves something to be desired, though, in that you don't get very good re-use if you are using accumulators from inside tracked functions. Right now that is treated as an untracked read, so if you want to get good re-use you need a workaround like this one...
```rust
#[salsa::tracked(return_ref)]
fn accumulated_values(db: &dyn Db) -> Vec<T> {
some_query::accumulated::<SomeAccumulator>(db)
}
```
...which would track and compare the new vs old vector and detect when they've changed.
Despite this limitation, this PR makes accumulators behave correctly with respect to the value taht gets returned and is good enough to Fix #313 in my opinion. I'll file an issue for the remaining improvements.
> Accumulators

- components/salsa-2022-macros/src/accumulator.rs
- components/salsa-2022-macros/src/jar.rs
- components/salsa-2022-macros/src/options.rs
- components/salsa-2022-macros/src/salsa_struct.rs
- components/salsa-2022-macros/src/tracked_fn.rs
- components/salsa-2022/src/function/lru.rs
- salsa-2022-tests/tests/lru.rs
- salsa-2022-tests/tests/mutate_in_place.rs
fixes #344 
Now we can write something like the following to set the lru capacity of tracked functions  
```rust
#[salsa::tracked(lru=32)]
fn my_tracked_fn(db: &dyn crate::Db, ...) { }
```
some details:  
* lru should not be combined with specify. We will report an error if people do #[salsa::tracked(lru = 32, specify)]
* set 0 as default capacity to disable LRU (Because I think doing this would make the code simpler when implementing `create_ingredients` of tracked functions).
* old salsa support to change lru capacity at runtime, [as noted here](https://salsa-rs.github.io/salsa/rfcs/RFC0004-LRU.html?highlight=change#reference-guide), but we do not support this now
> Add options to tracked funcitons for lru capacity 

- components/salsa-2022/src/id.rs
I made it private 'just because', but it turns out that dada uses it, and it seems reasonable.
> make Id::from_u32 public

- components/salsa-2022/src/id.rs
Make it easy to create an `Id`, especially from a `usize`
> add from impls for u32/usize

- book/src/tutorial/ir.md
Looking at the tutorial, I believe `ProgramSource` is a typo for `SourceProgram`. I'm also pretty sure the `define` -> `derive` is correct, unless `define` is some attribute I'm not aware of.
> fix: typos in tutorial ir chapter

- components/salsa-2022-macros/src/accumulator.rs
- components/salsa-2022-macros/src/input.rs
- components/salsa-2022-macros/src/interned.rs
- components/salsa-2022-macros/src/jar.rs
- components/salsa-2022-macros/src/options.rs
- components/salsa-2022-macros/src/salsa_struct.rs
- components/salsa-2022-macros/src/tracked_fn.rs
- components/salsa-2022-macros/src/tracked_struct.rs
- salsa-2022-tests/tests/override_new_get_set.rs
The goal is to add an option `constructor_name` to `#[salsa::input]`, `#[salsa::interned]` and `#[salsa::tracked]` that allows changing the name of the generated constructor. After that add attributes `get` and `set` to the fields which allow overriding the names of the getters and setters. In the end the following snippet should compile and work:
```rust
#[salsa::interned(constructor = from_string)]
struct MyInterned {
#[get(text)] #[set(set_text)] #[return_ref]
field: String,
}
impl MyInterned {
pub fn new(db: &dyn Db, s: impl Display) -> MyInterned {
MyInterned::from_string(db, s.to_string())
}
pub fn field(self, db: &dyn Db) -> &str {
self.text(db)
}
pub fn set_field(self, db: &mut dyn Db, id: String) {
self.set_text(&mut db, id)
}
}
```
resolves #332
> Permit renaming constructors, getters and setters

- Cargo.toml
- components/salsa-2022-macros/Cargo.toml
- components/salsa-2022-macros/src/salsa_struct.rs
- components/salsa-2022/Cargo.toml
- components/salsa-macros/Cargo.toml
- components/salsa-macros/src/database_storage.rs
- components/salsa-macros/src/query_group.rs
- tests/cycles.rs
- tests/incremental/memoized_volatile.rs
- tests/parallel/parallel_cycle_all_recover.rs
- tests/parallel/parallel_cycle_mid_recover.rs
- tests/parallel/parallel_cycle_none_recover.rs
- tests/parallel/parallel_cycle_one_recovers.rs
- Unify `parking_log` versions
- `test-env-log` has been renamed
- Update `heck`, `dashmap` and `hashlink` to theirs latest versions
With this `cargo tree --workspace --duplicates` now doesn't return anything, when in master it returned:
```
env_logger v0.7.1
[dev-dependencies]
└── salsa v0.17.0-pre.2 (/home/berni/Documents/src/salsa)
env_logger v0.9.0
└── salsa-2022-tests v0.1.0 (/home/berni/Documents/src/salsa/salsa-2022-tests)
getrandom v0.1.16
├── rand v0.7.3
│   └── rand_distr v0.2.2
│       [dev-dependencies]
│       └── salsa v0.17.0-pre.2 (/home/berni/Documents/src/salsa)
│   [dev-dependencies]
│   └── salsa v0.17.0-pre.2 (/home/berni/Documents/src/salsa)
└── rand_core v0.5.1
├── rand v0.7.3 (*)
└── rand_chacha v0.2.2
└── rand v0.7.3 (*)
getrandom v0.2.7
└── ahash v0.7.6
└── …
```
> Cargo updates

- components/salsa-2022-macros/src/input.rs
- components/salsa-2022-macros/src/interned.rs
- components/salsa-2022-macros/src/salsa_struct.rs
- components/salsa-2022-macros/src/tracked_struct.rs
This allows adding new options exclusively to `tracked`, `input`, `interned`, or any combination of them, without having to add support code to `SalsaStruct`.
The motivating example is #337, where `input` needs to accept a new `singleton` option, but `tracked` and `interned` should reject it.
> Have users of `SalsaStruct` specify allowed options

- components/salsa-2022-macros/src/salsa_struct.rs
- salsa-2022-tests/tests/warnings/main.rs
- salsa-2022-tests/tests/warnings/needless_borrow.rs
- salsa-2022-tests/tests/warnings/unused_variable_db.rs
Addresses a couple of warnings that appear when I tried to use current master in https://github.com/dada-lang/dada.
Also added tests that will fail to compile if the macros generate warnings.
> avoid warnings in generated code

- calc-example/calc/src/ir.rs
- components/salsa-2022-macros/src/input.rs
- components/salsa-2022-macros/src/interned.rs
- components/salsa-2022-macros/src/salsa_struct.rs
- components/salsa-2022-macros/src/tracked_struct.rs
- salsa-2022-tests/tests/compile-fail/get-set-on-private-field.rs
- salsa-2022-tests/tests/compile-fail/get-set-on-private-field.stderr
resolves #398 
Currently `#[salsa::input]` and `#[salsa::tracked]` structs made all getters and setters public, regardless of the visibility of the field and the getters for `#[salsa::interned]` had the visibility of the struct itself. This pull request changes the generated impl's to use the visibility of each field for it's getters and setters.
> Make getters and setters have the visibility of their field

- components/salsa-2022-macros/Cargo.toml
- components/salsa-2022-macros/src/tracked.rs
- components/salsa-2022-macros/src/tracked_fn.rs
- components/salsa-2022-macros/src/tracked_struct.rs
- salsa-2022-tests/tests/compile-fail/tracked_method_on_untracked_impl.rs
- salsa-2022-tests/tests/compile-fail/tracked_method_on_untracked_impl.stderr
- salsa-2022-tests/tests/tracked_method.rs
Fixes #319.
This allows users to annotate impl blocks with `#[salsa::tracked]` and
then create tracked methods by marking individual functions with
`#[salsa::tracked]`.
Note this requires your code that looks like:
```rust
#[salsa::tracked(jar = Jar)]
impl MyInput {
#[salsa::tracked]
fn tracked_fn(self, db: &dyn Db) -> u32 {
self.field(db) * 2
}
}
```
You get an error if you annotate a method with `#[salsa::tracked]` but forget to mark the impl block.
It got messier than I was hoping but I think it turned out alright, this would look really pretty if we had [inherent associated types](https://github.com/rust-lang/rust/issues/8995), but we don't. Annoyingly even if that landed I think we'd still need the attribute on the impl block just so that it was possible to create the associated …
> Allow creation of tracked methods

- components/salsa-2022-macros/src/input.rs
https://github.com/salsa-rs/salsa/pull/342 added `InputFieldIngredient` which replaces the `FunctionIngredient` for `salsa::input`, so we don't need to generate a config struct and `salsa::function::Configuration` impl for each field, beacuse they are only needed when we use `FunctionIngredient`
> no need to generate a config struct for each field of `salsa::input`

- components/salsa-2022-macros/src/tracked_fn.rs
- components/salsa-2022/src/salsa_struct.rs
- salsa-2022-tests/tests/tracked_fn_constant.rs
Fixes #323.
This adds support for tracked functions with only a database as input,
that is, it does not take a salsa struct.
I'm not entirely convinced by this, it feels like it works somewhat accidentally and may be fragile to changes. I'm happy if this just get closed as I was mostly playing around to see how this worked.
This change has the odd side-effect of making this code work:
```rust
#[salsa::tracked]
fn tracked_fn(db: &dyn Db, unit: ()) -> u32 {
44
}
```
> Allow "constant" tracked functions

- salsa-2022-tests/tests/compile-fail/accumulator_fields_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/accumulator_fields_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/accumulator_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/accumulator_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/input_struct_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/input_struct_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/interned_struct_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/interned_struct_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/jars_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/jars_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/salsa_fields_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/salsa_fields_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/tracked_fn_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/tracked_fn_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/tracked_impl_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/tracked_impl_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/tracked_method_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/tracked_method_incompatibles.stderr
- salsa-2022-tests/tests/compile-fail/tracked_struct_incompatibles.rs
- salsa-2022-tests/tests/compile-fail/tracked_struct_incompatibles.stderr
Used `trybuild` to verify that incompatible options with salsa structs will not compile
Ref: #354 
I created a `.rs` file for each salsa struct. I decided not to create one for each incompatible option, as this would only greatly increase the number of files.
> Exhaustive macros test

- calc-example/calc/src/parser.rs
- components/salsa-2022-macros/src/input.rs
- components/salsa-2022-macros/src/interned.rs
- components/salsa-2022-macros/src/salsa_struct.rs
- components/salsa-2022-macros/src/tracked_struct.rs
- components/salsa-2022/src/debug.rs
- components/salsa-2022/src/event.rs
- components/salsa-2022/src/key.rs
- salsa-2022-tests/tests/debug.rs
- salsa-2022-tests/tests/warnings/needless_borrow.rs
This addresses a couple of items of #397 
I initially added a separate `DebugWithDb::fmt_all` method but then changed it to an extra parameter to make it easier to propagate to inner fields. Also tried introducing something like:
```rust
pub struct FormatterWithDb<'me, 'f, Db: ?Sized>{
fmt: &'me mut std::fmt::Formatter<'f>,
db: &'me Db,
include_all_fields: bool
}
```
to pass to `fmt`, but I gave up because the lifetimes got a bit unwieldy.
> Include only identity fields by default in `DebugWithDb::debug` and add `DebugWithDb::debug_all`

- components/salsa-2022-macros/src/input.rs
- salsa-2022-tests/tests/input_with_ids.rs
This PR fixes an issue with code generation for `#[salsa::input]` struct's `set_` methods. 
Consider the following code:
```rust
#[salsa::input(jar = Jar)]
struct BuggedInput {
#[id]
id: u32,
other: String,
}
```
This will expand to:
```rust
#[derive(Copy, Clone, PartialEq, PartialOrd, Eq, Ord, Hash, Debug)]
struct BuggedInput(salsa::Id);
impl BuggedInput {
// snip...
fn set_other<'db>(
self,
__db: &'db mut <Jar as salsa::jar::Jar<'_>>::DynDb,
) -> salsa::setter::Setter<'db, BuggedInput, u32> {
//                                       ^^^ wrong type (should be `String`)
let (__jar, __runtime) = <_ as salsa::storage::HasJar<Jar>>::jar_mut(__db);
let __ingredients =
<Jar as salsa::storage::HasIngredientsFor<BuggedInput>>::ingredient_mut(__jar);
salsa::setter::Setter::new(__runtime, self, …
```
> salsa 2022: fix input macro set_* being off by one if id field present

- salsa-2022-tests/tests/compile-fail/jars_incompatibles.stderr
Rust 1.68 changed how the help suggestion text renders, and shows a diff for the suggested change.
> Update trybuild tests

- components/salsa-2022-macros/src/tracked_fn.rs
- salsa-2022-tests/tests/warnings/main.rs
- salsa-2022-tests/tests/warnings/needless_lifetimes.rs
The tracked method generation adds an extra `__db` lifetime to the signature, but clippy complains that this lifetime can be elided in some cases, so add an allow to silence this warning.
Unfortunately clippy doesn't lint inside of the warning tests, so those tests don't do anything to check that no clippy warnings are generated.
> Allow `clippy::needless_lifetimes` on tracked method getters

- components/salsa-2022/src/id.rs
- salsa-2022-tests/tests/compile-fail/get-set-on-private-field.stderr
This change is motivated to allow interned structs to have default const instances and prefill them in db initialization.
A specific example is managing symbols as a salsa interned struct in a compiler implementation. By declaring keywords as `const` symbols, we can handle keywords without going through their internal representation as rustc does (ref: [rustc_span::symbol](https://github.com/rust-lang/rust/blob/master/compiler/rustc_span/src/symbol.rs)). 
Conceptually, it'd look like the one below.
```rust
#[salsa::interned]
pub struct Symbol {
data: String,
}
const SELF_SYM: Symbol = Symbol(salsa::Id::from_u32(1))
...
/// This function is called in db initialization.
fn prefill(db: &dyn HirDb) {
Symbol::new(db, "self".to_string());
...
}
```
> Change the constructor of `salsa::Id` to const fn

- components/salsa-2022/src/runtime/local_state.rs
- salsa-2022-tests/tests/panic-when-creating-tracked-struct-outside-of-tracked-fn.rs
> Improve assert message when creating a tracked struct outside of a tracked function

- book/_redirects
- book/netlify.sh
- book/src/caveat.md
related to #448 
As Salsa-2022 is no yet complete and it is still unstable, there are some users who continue to use the old version of Salsa, or prefer using it due to its more stable API. Therefore, I think it is necessary to re-deploy the book for the older version of Salsa.
I have deployed the book for the older version from commit [754eea8b5f8a31b1100ba313d59e41260b494225](https://github.com/salsa-rs/salsa/commit/754eea8b5f8a31b1100ba313d59e41260b494225)  of Salsa on https://old-salsa-rs.netlify.app/
> add a link to the older version of Salsa in the document

- .github/workflows/test.yml
- components/salsa-2022/Cargo.toml
> Add miri to CI

- book/src/tutorial/db.md
https://github.com/salsa-rs/salsa/commit/73102b1e8ed4f373fbd02f28dc7884b3d9de96b3 removed `ANCHOR: default_impl` from https://github.com/salsa-rs/salsa/blob/master/examples-2022/calc/src/db.rs, but it still in the book, which results in an confusing empty code block: https://salsa-rs.github.io/salsa/tutorial/db.html#implementing-the-default-trait
The struct is already has `#[derive(Default)]`, so at this point the section is not very useful. Maybe it is better without it?
> Remove `Implementing the Default trait` book section

- components/salsa-2022/src/storage.rs
> fix: wrong condvar usage

- book/src/cycles/fallback.md
This may have been true in the past, but both the Salsa 2022 and original tests demonstrate recovery from a cycle where only a subset of the cycle queries have recovery functions.
> Remove inaccurate note about mixed cycles failing to recover

- components/salsa-2022-macros/Cargo.toml
With the latest commit (283ccda), any project that uses Salsa hits tons
of internal errors within Salsa. That's because Salsa needs syn's `full`
feature, which was removed from the Cargo.toml as part of the Salsa 3.0
mega-PR. Because Salsa 1.0 still has the `full` feature in its
Cargo.toml, Cargo implicitly still enables `full` for Salsa 2022, and
thus the Salsa 2022 example projects compile fine -- even though any
external code using Salsa does not.
> Add missing `syn` feature requirement

- book/src/overview.md
- book/src/plumbing/db_lifetime.md
- book/src/tutorial/ir.md
> book: Creating inputs no longer requires `&mut dyn Db`

- src/id.rs
- src/routes.rs
- src/update.rs
Implement the `Update` trait for sets/maps
cc @camelid
> implement Update trait for sets/maps

- Cargo.toml
- components/salsa-macros/Cargo.toml
- src/function/lru.rs
- src/function/memo.rs
- tests/compile-fail/singleton_only_for_input.stderr
Follow-up of #501: removing some unused dependencies.
Relates to #504.
> Remove some unused dependencies

- .github/workflows/book.yml
- .github/workflows/test.yml
- bors.toml
Another follow-up of #501. 
Removes `bors.toml`, because it's no longer used/needed (it seems salsa is using a merge queue now). Also removes the empty `rustfmt.toml`.
Updates some GitHub Actions to the latest, removes the `bors` branch push triggers, and removes the use of the unmaintained `actions-rs` actions. Also bumps the `mdbook` versions to the latest and adds cacheing for the rust build jobs.
> Remove `bors.toml` and update GitHub Actions

- .github/workflows/book.yml
Follow-up of #507, fixes `Error: Error message: Unable to get ACTIONS_ID_TOKEN_REQUEST_URL env variable` and limits concurrency of deploy jobs.
> Add required book deploy permissions and add concurrency group

- src/update.rs
This is useful in code that uses typestate.
> Impl `Update` for unit type `()`

- components/salsa-macro-rules/src/setup_interned_struct.rs
- tests/compile-fail/specify-does-not-work-if-the-key-is-a-salsa-interned.stderr
- tests/tracked_fn_on_interned.rs
This fixes the second part of https://github.com/salsa-rs/salsa/issues/521 where tracked functions didn't accept interned values
> Allow interned values as tracked function arguments

- Cargo.toml
- src/tracked_struct/struct_map.rs
Update `dashmap`, `hashlink` and `rustc-hash` to the most recent major version.
**dashmap**
> This release contains performance optimizations, most notably 10-40% gains on Apple Silicon but also 5-10% gains when measured in Intel Sapphire Rapids. This work was accomplished in:
It's a major because there's a slight API change. 
**hashlink**
> API incompatible change: Don't panic in reserve and try_reserve in cases where a rehash is needed. Previously would panic, adds the proper bounds on reserve methods to do a rehash (previously bounds were missing, and reserve would result in panics). (Thank you cuviper!)
I think that's fine
**rustc-hash**
> Replace hash with faster and better finalized hash. This replaces the previous "fxhash" algorithm originating in Firefox with a custom hasher …
> Update `dashmap`, `hashlink`, and `rustc-hash`

- src/database.rs
- tests/synthetic_write.rs
This PR fixes `db.synthetic_write` by bumping the `runtime.revision`. 
This wasn't needed before because `runtime_mut` went through `jars_mut` which increments the revision. 
Since this is no longer the case, bump the revision manually. 
I verified that the test failed *before* making the change.
> Bump revision in `db.synthetic_write`

- src/handle.rs
This PR adds a `into_inner` function to `Handle`. 
Being able to go back to the database can be useful for methods that take a `Database` as argument but have to create a `Handle` because they run concurrent code. 
It is then desired that the method can return a `Database` to avoid that the entire code base has to use a `Handle<Db>`. 
Example:
```rust
#[allow(clippy::print_stderr)]
fn run(mut self, db: RootDatabase) -> RootDatabase {
// Schedule the first check.
let mut db = salsa::Handle::new(db);
self.sender.send(MainLoopMessage::CheckWorkspace).unwrap();
let mut revision = 0usize;
while let Ok(message) = self.receiver.recv() {
tracing::trace!("Main Loop: Tick");
match message {
MainLoopMessage::CheckWorkspace => {
let db = db.clone();
let sender = self.sender.clone();
// Spawn a new …
```
> Add Handle::into_inner method

- src/local_state.rs
Working on https://github.com/salsa-rs/salsa/pull/529 I ran into the issue that the assertion in `DbGuard` asserting that the DB is unchanged consistently fails. 
The underlying problem is that `NonNull::eq` not only compares the pointer but also the metadata which is unreliable for trait object pointers
> When comparing wide pointers, both the address and the metadata are tested for equality. However, note that comparing trait object pointers (*const dyn Trait) is unreliable: pointers to values of the same underlying type can compare inequal (because vtables are duplicated in multiple codegen units), and pointers to values of different underlying type can compare equal (since identical vtables can be deduplicated within a codegen unit). …
> Fix assertion for same DB in `DbGuard`

- Cargo.toml
- benches/incremental.rs
This PR adds a micro-benchmark that measures the cost of validating many tracked structs that are all unaffected by the input change. 
The benchmark is emulating a scenario where a root query creates a large number of tracked structs, e.g., a `program.check` call. Now, a single file changes that invalidates a very small subset of ingredients, but `program.check` still pays the cost of marking unchanged ingredients as "validated".
I back-ported the benchmark to before *beautiful Salsa*. See https://github.com/salsa-rs/salsa/pull/530. 
Running the benchmark on the current version takes around 14us whereas the pre-rewrite version only takes 12us on my machine. 
This benchmark covers https://salsa.zulipchat.com/#narrow/stream/333573-salsa-3.2E0/topic/Beautiful.20Salsa.20perf.20incremental.20ch …
> Add benchmark for query with many tracked structs

- .github/workflows/test.yml
- Cargo.toml
- benches/incremental.rs
This PR is based on https://github.com/salsa-rs/salsa/pull/529
This PR adds a CI step to run the benchmarks with codspeed. This gives us a similar experience to https://github.com/astral-sh/ruff/pull/12406#issuecomment-2241067701
I don't have the necessary permissions to finish the setup myself. 
1. [Add the repository to codspeed](https://docs.codspeed.io/importing-repositories)
2. [Add the access token](https://docs.codspeed.io/ci/github-actions) (named `CODSPEED_TOKEN`)
We'll need to create a access token and add it. I don't have the necessary permissions. See
> Add CodSpeed Benchmarks to CI

- examples/calc/parser.rs
The `expect!` tests for the parser example are failing in main branch. This failure started with https://github.com/salsa-rs/salsa/commit/c50cefa71e24ccdd108576938dfa44139fc72c00 which upgraded the `ordered-float` dependency. It looks like the new version of ordered-float implements `Display` as a pass-through to the underlying float, and the old version did not, causing these test failures.
Generated by running `env UPDATE_EXPECT=1 cargo test --workspace --all-features --all-targets`.
> Update expect test output to account for OrderedFloat changes

- examples/calc/parser.rs
- src/array.rs
- src/input.rs
I found this really useful in debugging durability issues; it allows sprinkling a `dbg!(&data.stamps)` in some key places to see what the field durabilities and changed-at values are for the fields.
> Require Debug for C::Stamps

- .github/workflows/test.yml
This will prevent clippy warnings collected un-noticed in main branch.
> Add -D warnings to clippy CI

- Cargo.toml
- src/active_query.rs
- src/cycle.rs
- src/function.rs
- src/zalsa_local.rs
- tests/cycles.rs
This PR does two things:
1) Add the `trace` feature for the `test-log` dependency, which I've found very useful in trying to understand the cycle-handling code. It means that I can change `#[test]` to `#[test_log::test]` above a failing test of interest, and then if I run `cargo test` with e.g. `RUST_LOG=debug`, the failing test output will include all the debug traces from that test.
2) Fix up a bunch of comments and some debug traces I ran across in my exploration that looked out of date.
Happy to split this into two PRs if that's preferred.
> Add test tracing, fix up comments

- components/salsa-macro-rules/src/setup_tracked_fn.rs
Resolves https://github.com/salsa-rs/salsa/issues/547
> Fixed non_local_definitions warning

- components/salsa-macro-rules/src/setup_input_struct.rs
- src/input.rs
- src/input/setter.rs
- src/zalsa.rs
- tests/tracked_fn_high_durability_dependency.rs
This PR fixes a bug in Salsa where changing the value of a high durability field did not invalidate any queries with `durability > LOW` 
I had to re-expose `&mut Runtime` again when calling `ingredient_mut` to call `runtime.report_tracked_write` in `SetterImpl`
> Fix query invalidation when high durability input changes

- book/src/cycles/fallback.md
Update the book section on cycle fallbacks to match what actually worked for me with the current Salsa code in main branch.
> [book] fix the cycle fallback section to match current code

- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
This PR reduces the verbosity of Salsa's tracing output. 
Salsa used to include the `Memo` value in the tracing output. If the value is large (imagine a file's source text or AST), this can lead to very verbose traces.
This PR introduces a new `tracing_debug` function on `Memo` that omits `value` and only includes whether the `Memo`'s value is `Some` or `None`.
I considered chagning `Memo`'s `Debug` implementation but I can see cases where it might be useful to debug print a `Memo` including its value when debugging a Salsa issue. 
The output of `Memo.revisions` can still be long if a query has many dependencies but seeing the outputs is useful when debugging Salsa
I used a field-level tracing filter in Ruff and the Salsa output looks very manageable now.
```
RED_KNOT_LOG=[{name=bar.baz}] …
```
> Reduce tracing output of memo

- src/input.rs
- src/input/setter.rs
- tests/input_setter_preserves_durability.rs
This PR changes the `Setter` to preserve the existing durability instead of defaulting to `Low`. 
[Discussed on Zulip](https://salsa.zulipchat.com/#narrow/stream/333573-salsa-3.2E0/topic/durability/near/454842662)
> Preserve durability when setting a new input-value

- Cargo.toml
- benches/compare.rs
- examples/lazy-input/main.rs
Pulling from https://github.com/davidbarsky/salsa-benchmarks/; these should probably live in here.
> internal: add some initial input benchmarks

- src/active_query.rs
- src/function/execute.rs
- src/zalsa_local.rs
A small performance improvement to avoid cloning hash sets where we can consume the value instead.
> Reduce cloning of sets in `ActiveQuery` and `QueryRevisions`

- src/durability.rs
- src/function.rs
- src/id.rs
- src/interned.rs
- src/revision.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/zalsa.rs
Clippy's failing CI in other cases; might as well fix it.
I also changed some of the phrasing in the documentation.
> chore: fix clippy lints

- tests/tracked_struct_durability.rs
This brings over just the test from https://github.com/salsa-rs/salsa/pull/550, which was already fixed in https://github.com/salsa-rs/salsa/pull/564
> add test for high-durability dependency validation

- src/accumulator.rs
- src/accumulator/accumulated.rs
- src/accumulator/accumulated_map.rs
- src/active_query.rs
- src/function.rs
- src/function/accumulated.rs
- src/function/execute.rs
- src/function/fetch.rs
- src/function/input_outputs.rs
- src/function/maybe_changed_after.rs
- src/function/specify.rs
- src/hash.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/table.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/zalsa_local.rs
Refactor how accumulators are implemented. Instead of storing the values accumulated by a particular function X in a central map in the ingredient, attach them to the memo for X. This moves us a big step closer towards having *all* relevant data stored in tables and will help with speculative execution, lightweight dependencies, and a number of forward goals.
Review requested from @MichaReiser, if you have time, and others too =)
> Refactor accumulators

- src/active_query.rs
- src/function.rs
- src/function/diff_outputs.rs
- src/function/execute.rs
- src/function/fetch.rs
- src/function/specify.rs
- src/tracked_struct.rs
- src/zalsa_local.rs
- tests/tracked_struct_recreate_new_revision.rs
Edited by @MichaReiser 
This is an error that surfaced when working on Ruff's LSP. The scenario is:
* Revision 0: Query `Q` creates a tracked struct `S`
* Revision 1: Query `Q` no longer creates a tracked struct
* Revision 2: Query `Q` again creates a tracked struct `S`
The real world scenario is Ruff's semantic index that creates a tracked struct `Scope` for every function. Deleting a function and then creating a new function resulted in a panic `two concurrent writers to {id:?}, should not be possible`.
The root cause of the panic is that a removed entity is added to an ingredients-free list, but the ID is never removed from the `tracked_struct_ids`, resulting in Revision 2 re-using the struct from the free list.
> Fix panic when recreating tracked struct that was deleted in previous revision

- Cargo.toml
- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macros/src/interned.rs
- components/salsa-macros/src/salsa_struct.rs
- src/interned.rs
- src/lib.rs
- tests/interned-struct-with-lifetime.rs
- tests/interned-structs.rs
> Add a way to use reference-types in InternedStruct::new

- src/active_query.rs
- src/function/diff_outputs.rs
- src/tracked_struct.rs
- src/zalsa_local.rs
- tests/hash_collision.rs
> Add IngredientIndex to KeyStruct

- components/salsa-macros/src/tracked_fn.rs
- tests/compile-fail/tracked_fn_incompatibles.rs
- tests/compile-fail/tracked_fn_incompatibles.stderr
- tests/tracked_fn_read_own_specify.rs
Fixes #519
I think that there would be roughly two options for fixing this;
1. Returning error while proc macro expansion
2. Inserting a type alias like `type __T<'db> = DbInputArgType;` inside the expanded function's body so that the expanded code fails to compile
In this PR, I chose the first one because the second is little bit non-intuitive and the expanded code is slightly more bloated.
But the second one also has its own merit; It can utilize rustc's more detailed error message and is more consistent with the case that the other input parameter has an elided lifetime.
So, I'm okay to switch to the second one if I have to 😄
> fix: Inconsistent behaviour with lifetime elision on tracked fn

- components/salsa-macro-rules/Cargo.toml
This was breaking rust-analyzer's CI in https://github.com/rust-lang/rust-analyzer/pull/18305.
> chore: ensure salsa-macros have a licence

- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macros/src/salsa_struct.rs
Fixes the first point of https://github.com/salsa-rs/salsa/issues/586
> Improve the span used for salsa struct constructors

- components/salsa-macros/src/accumulator.rs
- components/salsa-macros/src/db.rs
- components/salsa-macros/src/input.rs
- components/salsa-macros/src/interned.rs
- components/salsa-macros/src/lib.rs
- components/salsa-macros/src/tracked.rs
- tests/compile-fail/input_struct_incompatibles.stderr
- tests/compile-fail/interned_struct_incompatibles.stderr
- tests/compile-fail/tracked_fn_incompatibles.stderr
- tests/compile-fail/tracked_impl_incompatibles.stderr
- tests/compile-fail/tracked_method_incompatibles.stderr
- tests/compile-fail/tracked_method_on_untracked_impl.stderr
fixes #580 by taking a similar strategy to https://github.com/tokio-rs/tokio/pull/4162/ 
i did this in all proc macros so that they would all work as well, however it is trivial to just dial this down to just tracked if that's desired. 
this however, does have a potential downside which is that the compiler error messages are a bit more verbose because rustc is now checking the input tokens as well if the macro expansion fails.  you can see these in the additional lines added to the compiler fail tests.
> salsa-macros: handle invalid inputs in a way friendlier to rust-analyzer

- components/salsa-macro-rules/src/setup_tracked_fn.rs
This + a change in rust-analyzer resolves the last thing in https://github.com/salsa-rs/salsa/issues/586
> Emit struct in `#[tracked]` fn last for better IDE support

- Cargo.toml
- benches/accumulator.rs
- src/accumulator/accumulated_map.rs
- src/active_query.rs
- src/function/accumulated.rs
- src/function/fetch.rs
- src/input.rs
- src/interned.rs
- src/tracked_struct.rs
- src/zalsa_local.rs
This PR implements faster accumulators. 
Accumulators are relatively costly today because collecting the accumulated values requires iterating over the queries' entire dependency tree. 
This cost is negligible with a cold DB but adds up for very deep trees. 
For example, adding accumulators to Ruff resulted in a 30% perf regression https://github.com/astral-sh/ruff/pull/14116
This PR adds a new field to `AccumulatedMap` that tracks whether any dependency of the current query has any accumulated values. It checks that field when collecting the accumulated values, allowing it to skip entire subtrees. 
This approach should make accumulated values nearly "free" in the common cases where there are no or only very few diagnostics. 
I added a benchmark and I verified that the perf regression in …
> Faster accumulators

- src/function/accumulated.rs
This PR uses the input-output length to approximate the number of items added to `stack` and reserves `stack.len()` additional items in `visited` to avoid costly resizes. This reduces the performance regression in https://github.com/astral-sh/ruff/pull/14760 from 10.3% to 9%, which seems worthwhile.
The downside is that it can result in a too large `stack` if a query has many outputs but only few outputs or in a too large `visited` set if many inputs are overlapping. I think this is acceptable, considering that the data structures are short-lived. 
This shows a 9% performance improvement for the [accumulator benchmark](https://codspeed.io/salsa-rs/salsa/branches/MichaReiser%3Asmall-accumulator-perf?uri=benches%2Faccumulator.rs%3A%3Abenches%3A%3Aaccumulator%3A%3Aaccumulator).
> Approximate sizes of `stack` and `visisted` when collecting accumulated values

- src/runtime.rs
- src/runtime/dependency_graph.rs
- src/zalsa_local.rs
This removes a couple panic paths
> Remove unnecessary `Option` from `ZalsaLocal::query_stack`

- src/table.rs
No need to use a `Vec` here, we have a comptime length of the page so we unnecessarily store an extra length and capacity
> Replace `Page` data Vec with boxed fixed array

- src/interned.rs
split out from https://github.com/salsa-rs/salsa/pull/633, thes two hash impls ought to delegate to the slice impl, as `Vec`s do, notably slices hash their length as well which this code does not.
> Fix `Lookup<Vec<T>>` impls

- components/salsa-macro-rules/src/setup_input_struct.rs
- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macro-rules/src/setup_tracked_struct.rs
- src/accumulator.rs
- src/function.rs
- src/ingredient.rs
- src/input.rs
- src/interned.rs
- src/salsa_struct.rs
- src/tracked_struct.rs
- src/zalsa.rs
- tests/tracked_fn_multiple_args.rs
> Assign memo ingredients per salsa-struct-ingredient

- Cargo.toml
- src/accumulator.rs
- src/active_query.rs
- src/function/accumulated.rs
- src/function/memo.rs
- src/key.rs
- src/table/memo.rs
- src/zalsa_local.rs
`QueryEdges` were `Arc`ed before, but we only ever clone them for LRU evictions (and there the original one will drop right after eviction), this is a rare occurence. Additionally to save on constantly allocating an empty `Arc` in the case where no deps exist, we needed a `lazy_static`. Instead, we `Box` the slice now, dropping the need for ref-counting as well as the `lazy_static` as an empty slice never allocates in a `Box`. 
Another improvement we should make is use a `ThinBox` once that's a thing, we don't really make use of the length directly and it would shave off 4/8 bytes for Memo/QueryRevisions.
> Replace unnecessary `Arc` by `Box`

- tests/parallel/parallel_map.rs
- tests/parallel/signal.rs
As discovered in https://github.com/salsa-rs/salsa/pull/635, the test here is racy. After resolving the `wait_for` it never actually executes cancellable work and so it might just finish computation without cancelling (the only place where it was able to cancel was when calling the `input.field(db)` call. This brings the test more in line with how `parallel_execute` does it.
> Fix parallel_map::execute_cancellation test

- src/storage.rs
We can enforce the drop order via generated drop glue instead
> Remove unnecessary `Option` around `Storage::zalsa_impl`

- src/accumulator.rs
- src/active_query.rs
- src/cycle.rs
- src/event.rs
- src/function.rs
- src/function/diff_outputs.rs
- src/function/maybe_changed_after.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/runtime.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/zalsa_local.rs
Output edges can never contain a `None` key index so `mark_validated_output` and `remove_stale_output` unwrap these options. We can easily get around that with a bit more strict typing though.
> Remove unreachable unwraps via typing

- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- src/input.rs
- src/interned.rs
- src/lib.rs
- src/table.rs
- src/tracked_struct.rs
- src/zalsa_local.rs
- tests/interned-structs_self_ref.rs
This lacks a user facing API via the macro but I could not be bothered implementing that as it takes way too much effort with the decl macro quoting unfortunately (and I did not feel like cloning the entire macro for this either). This is enough for rust-analyzer's needs for the time being though as there is only one usage which we have handwritten for now.
> Implement self-referential/subset key interning 

- src/database.rs
This method is used all over rust-analyzer, most prominently in rust-analyzer's `parallel_prime_caches` method. We use this method in order to check for cancellation in an ad-hoc, map/reduce-shaped threadpool inside of `parallel_prime_caches`, and (re)introducing this method solves a hang there.
> feature: expose `Database::unwind_if_revision_cancelled`

- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macros/src/tracked_fn.rs
This change allows rust-analyzer (and, I assume RustRover) to provide accurate completions inside of a `#[salsa::tracked]` function. Previously, I'd comment out the `#[salsa::tracked]` annotation when writing a tracked function, but this PR removes the need for that workaround.
As @Veykril put it, the _core_ issue is that rust-analyzer's `mbe` crate is not very error-resilient: we no longer pick the correct match arm of the `macro_rules` macro because the input doesn't match—`mbe` _should_ pick the closest match instead of giving up, but until `mbe` supports that, this PR ~~papers over a rust-analyzer weakness~~ 🌟  it makes the macro more IDE friendly 🌟 !
(Credit goes to Lukas for the tip, explanation, and joke!)
> chore: fix completions in `#[salsa::tracked]` functions

- book/src/overview.md
*Like* an input, the new for a tracked struct only requires a &-reference to the database:
> Out of date comment in overview

- components/salsa-macro-rules/src/setup_input_struct.rs
- src/input.rs
- src/input/singleton.rs
- src/lib.rs
This does some type shenanigans (unfortunately can't gate on the previously used const as Rust's const story just isn't there yet), to swap the singleton field with `()` if it's not needed.
> Do not allocate input singleton data for non-singleton inputs

- src/accumulator.rs
- src/accumulator/accumulated_map.rs
- src/active_query.rs
- src/function.rs
- src/function/accumulated.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/zalsa_local.rs
- tests/accumulated_backdate.rs
Rebased version of https://github.com/salsa-rs/salsa/pull/641
> Fix accumulated values for backdated queries

- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macros/src/accumulator.rs
- components/salsa-macros/src/input.rs
- components/salsa-macros/src/interned.rs
- components/salsa-macros/src/options.rs
- components/salsa-macros/src/salsa_struct.rs
- components/salsa-macros/src/tracked_fn.rs
- components/salsa-macros/src/tracked_struct.rs
- src/id.rs
- tests/interned-structs.rs
This PR adds support for three features:
1. Writing `#[salsa::interned(no_lifetime)]` allows skipping the `'db` lifetime.
2. `#[salsa::interned]` structs now have public ingredients, which allows accessing the underlying, interned data through the `salsa::Id` alone.
3. Adds support for custom Salsa IDs. While rust-analyzer doesn't need this, their presence makes migration easier. I'd like to jettison this feature before the 1.0 release.
In my view, the use of the above features should be discouraged, but they are necessary for rust-analyzer to migrate to the new version of Salsa.
This PR supersedes https://github.com/salsa-rs/salsa/pull/632.
> feature: allow skipping the lifetime on `#[salsa::interned]` structs

- Cargo.toml
- components/salsa-macro-rules/src/setup_input_struct.rs
- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- src/database_impl.rs
- src/input.rs
- src/interned.rs
- src/lib.rs
- src/storage.rs
- src/table.rs
- src/tracked_struct.rs
- tests/debug_db_contents.rs
- tests/interned-structs_self_ref.rs
As discussed in [this HackMD](https://hackmd.io/3Mpv0fa7Rm6cn9-EH5ejkw), we want to dump the contents of a Salsa database in order to debug what rust-analyzer and Salsa are doing. The original Salsa had a [`DebugQueryTable`](https://github.com/rust-lang/rust-analyzer/blob/fa4a40bbe867ed54f5a7c905b591fd7d60ba35eb/crates/ra-salsa/src/debug.rs#L9-L29) that we'd use [like this](https://github.com/rust-lang/rust-analyzer/blob/0a706f7d2ac093985eae317781200689cfd48b78/crates/rust-analyzer/src/cli/analysis_stats.rs#L274-L286):
```rust
let mut total_file_size = Bytes::default();
for e in ide_db::base_db::ParseQuery.in_db(db).entries::<Vec<_>>() {
total_file_size += syntax_len(db.parse(e.key).syntax_node())
}
let mut total_macro_file_size = Bytes::default();
for e in …
```
> feature: Add support for dumping database contents

- benches/compare.rs
They used to create a new database for each iteration, which means the ingredients were re-created each time, which is very much not like real-world use-cases, where (besides testing) it is usually created once.
> Fix benchmarks

- components/salsa-macro-rules/src/setup_tracked_struct.rs
- components/salsa-macros/src/input.rs
- components/salsa-macros/src/interned.rs
- components/salsa-macros/src/salsa_struct.rs
- components/salsa-macros/src/tracked_struct.rs
- examples/calc/ir.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- tests/compile-fail/input_struct_incompatibles.rs
- tests/compile-fail/input_struct_incompatibles.stderr
- tests/compile-fail/interned_struct_incompatibles.rs
- tests/compile-fail/interned_struct_incompatibles.stderr
- tests/deletion-drops.rs
- tests/expect_reuse_field_x_of_a_tracked_struct_changes_but_fn_depends_on_field_y.rs
- tests/expect_reuse_field_x_of_an_input_changes_but_fn_depends_on_field_y.rs
- tests/preverify-struct-with-leaked-data-2.rs
- tests/preverify-struct-with-leaked-data.rs
- tests/tracked-struct-id-field-bad-eq.rs
- tests/tracked-struct-id-field-bad-hash.rs
- tests/tracked-struct-value-field-bad-eq.rs
- tests/tracked-struct-value-field-not-eq.rs
- tests/tracked_struct_durability.rs
- tests/tracked_struct_mixed_tracked_fields.rs
- tests/tracked_with_intern.rs
- tests/tracked_with_struct_db.rs
This PR makes tracked structs coarse-grained by default. To declare a field independently tracked, you now use the `#[tracked]` attribute. This is the opposite of the previous behavior, where `#[id]` effectively declared a field untracked. The `#[id]` attribute now has no effect. Importantly, reads of untracked fields do not require a read dependency to be declared.
There is some duplicated code in the macros as we need to generate separate accessors for tracked vs. untracked fields and I would like these to be static (as opposed to branching at runtime).
I believe the guide documentation also needs to be updated.
Resolves https://github.com/salsa-rs/salsa/issues/598.
> Coarse-grained tracked structs

- src/interned.rs
Fixes https://github.com/salsa-rs/salsa/issues/670
> Impl `HashEqLike<T>` for `&T`

- components/salsa-macro-rules/src/setup_input_struct.rs
- src/function.rs
- src/update.rs
- tests/compile-fail/tracked_fn_return_ref.rs
- tests/compile-fail/tracked_fn_return_ref.stderr
- tests/cycles.rs
- tests/lru.rs
- tests/warnings/needless_lifetimes.rs
Fixes https://github.com/salsa-rs/salsa/issues/610 by requiring the `Output` of tracked functions to implement `Update`
Let's see how annoying this will be...
> Require `Update` trait for tracked function return values

- src/input.rs
- src/interned.rs
- src/storage.rs
- src/tracked_struct.rs
- tests/debug_db_contents.rs
This PR redesigns the functionality introduced in #640 so that the dump-all-database contents methods are on the Salsa struct ingredient instead of the database's `Storage`. I think this is an improvement for two reasons:
1. This design is closer to the original [`DebugQueryTable`](https://docs.rs/salsa/0.16.1/salsa/debug/trait.DebugQueryTable.html) trait.
2. At least within rust-analyzer, it's not feasible to get access to the underlying storage from methods that only have a `&dyn SomeDatabase`. However, it _is_ feasible to access the ingredient
Here's an example for interned structs (input and tracked structs have an identical API): 
```rust
#[salsa::interned]
struct InternedStruct<'db> {
name: String,
}
let _ = InternedStruct::new(&db, "Hello, world!".to_string());
let interned = …
```
> feature: expose database contents as inherent method on Ingredients

- src/interned.rs
- tests/interned-structs.rs
It looks like the fix in https://github.com/salsa-rs/salsa/pull/671 was the wrong way around, I should have confirmed that it fixed the regression.
> Implement `HashEqLike<&T>` for `T`

- src/tracked_struct.rs
- src/update.rs
- tests/tracked_struct_disambiguates.rs
As was raised by @ibraheemdev in https://github.com/salsa-rs/salsa/pull/647, the hashmap may consider slots/buckets that do not uniquely correspond to a single hash so the hash itself is required for equality in our case.
Added a test that exerts the disambiguator mapping as we have no test that actually hits it, though even without the changes here that test won't fail. I am not quite sure what a setup for that would be.
> Fix Disambiguator- and IdentityMap hashing

- Cargo.toml
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macros/src/tracked_fn.rs
- components/salsa-macros/src/update.rs
- examples/calc/ir.rs
- src/function.rs
- src/update.rs
- tests/compile-fail/tracked_fn_return_ref.rs
- tests/compile-fail/tracked_fn_return_ref.stderr
- tests/lru.rs
- tests/tracked_struct.rs
- tests/warnings/needless_lifetimes.rs
Use the Fallback trick similar to what the `derive(Update)` does to constrain the tracked-fn's return type to `Update`. 
This removes the need to implement `Update` for types with a `'static` lifetime.
I also added a few `Update` implementations that are needed for Ruff. The not good news is, Ruff now panics with some assertions and I haven't figured out the root cause yet. 
Edit: Okay, the panics go away if I back out of the coarse-grained dependency changes... So something goes wrong there, uff.
> Use *fallback* trick for tracked-fn `Update` constraint

- Cargo.toml
- examples/lazy-input/main.rs
- src/accumulator/accumulated_map.rs
- src/active_query.rs
- src/function/delete.rs
- src/function/lru.rs
- src/function/memo.rs
- src/function/specify.rs
- src/input.rs
- src/input/singleton.rs
- src/revision.rs
- src/tracked_struct.rs
- src/zalsa_local.rs
- tests/parallel/parallel_cancellation.rs
- tests/parallel/parallel_cycle_all_recover.rs
- tests/parallel/parallel_cycle_mid_recover.rs
- tests/parallel/parallel_cycle_none_recover.rs
- tests/parallel/parallel_cycle_one_recover.rs
- tests/parallel/parallel_map.rs
- tests/parallel/setup.rs
I believe Ibrahim talked about this and it seemed reasonable to me to do. This just carries over the orderings that atomic cell uses for now (with one exception). We also drop the crossbeam dependency now, replacing it with `crossbeam-queue` and `crossbeam-channel`.
> Replace all uses of `AtomicCell` with appropriate atomic primitives

- src/accumulator.rs
- src/function.rs
- src/function/fetch.rs
- src/function/lru.rs
- src/function/memo.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/runtime.rs
- src/table.rs
- src/table/memo.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/zalsa.rs
- tests/lru.rs
This change makes us LRU evict once a new revision starts, instead of at the very moment we reach the limit while computing tracked functions.
> LRU eviction at revision bump

- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macros/src/tracked_fn.rs
- tests/compile-fail/tracked_fn_return_ref.rs
- tests/compile-fail/tracked_fn_return_ref.stderr
I also slimmed down the generated code for this given it shouldn't be called in the first place, so it being a no-op doesn't matter
> Emit better diagnostic for invalid tracked function return types

- Cargo.toml
- src/input.rs
- src/interned.rs
- src/table.rs
- src/tracked_struct.rs
- src/views.rs
- src/zalsa.rs
Boxcar now uses [Loom](https://github.com/ibraheemdev/boxcar/pull/25), and I personally trust Loom/Shuttle-tested libraries more than those that aren't despite their apparent simplicity.
(cc: @ibraheemdev)
> internal: switch to `boxcar` from `append-only-vec`

- .github/workflows/release.yml
- README.md
This PR adds a GitHub Actions workflow for publishing crate to crates.io.
Once merged this PR, remember to :
1. Go to crates.io and generate a token.
2. Open repository settings on GitHub.
3. Select the "Actions" under the "Secrets and variables":
4. Create a repository secret called `CARGO_REGISTRY_TOKEN` and paste the token into there.
To publish a new version to crates.io, just update the `version` field of Cargo.toml and create a corresponding Git tag.
Hope it helps. I'm looking forward to new versions of Salsa.
Close #489
> add release workflow

- Cargo.toml
- examples/calc/ir.rs
- examples/calc/type_check.rs
This was only used for 4 structs in the `calc` example and the expanded code isn't that large.
> Remove dev dependency `derive-new`

- Cargo.toml
https://github.com/salsa-rs/salsa/actions/runs/13416786546/job/37479444250 is failed due to lack of `version` of `salsa-macros` in Cargo manifest. This PR fixes it.
> fix: fix missing version in Cargo manifest

- Cargo.toml
This leaves only `dashmap` pulling in the 0.14 series of `hashbrown`.
> Update `hashbrown` (0.15) and `hashlink` (0.10)

- components/salsa-macro-rules/src/setup_input_struct.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- src/accumulator.rs
- src/database.rs
- src/function.rs
- src/function/lru.rs
- src/function/memo.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/runtime.rs
- src/storage.rs
- src/table/sync.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/zalsa.rs
- src/zalsa_local.rs
- tests/lru.rs
Best reviewed by commit as it contains a couple cleanup commits
> Allow triggering LRU eviction without increasing the current revision

- src/database.rs
- src/function/diff_outputs.rs
- src/function/execute.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/key.rs
- src/table/sync.rs
- src/tracked_struct.rs
Instead pass around `&Zalsa` to callers more to reduce dynamic dispatch, in most of these cases the functions are only called once so the compiler should have enough knowledge to make the extra argument passing virtually free
> Remove some `ZalsaDatabase::zalsa` calls

- .github/workflows/test.yml
- Cargo.toml
- tests/compile_fail.rs
We specified an MSRV of 1.76 in `Cargo.toml`, but this was a lie, because it wasn't tested anywhere.
This updates our MSRV to 1.80, the oldest Rust that current main branch actually compiles on, and adds a CI run on 1.80 so that it's tested.
This requires also updating the `rustversion` macro on the `compile_fail` test so that it runs only on stable Rust later than 1.84; that test snapshots compiler output and fails on any Rust version earlier than 1.84.
(Over in #603 I asked about upping our MSRV to 1.83, but the first step is to actually have an MSRV that isn't a lie.)
> update MSRV to 1.80 and test it in CI

- src/function.rs
- src/lib.rs
- src/table.rs
- src/update.rs
- src/views.rs
We'll need to do this for the 2024 edition upgrade. The motivation for this change thouhgh is so I can quickly check whether the merge queue works now (and so I'll self approve this)
> Enforce `unsafe_op_in_unsafe_fn`

- src/accumulator.rs
- src/storage.rs
- src/table.rs
- src/zalsa_local.rs
Currently when creating a new `ZalsaLocal` struct, using it and dropping it (which is going to be a common scenario for rust-analyzer where we effectively create one per LSP request) we will allocate pages when required for allocating a new salsa struct and then drop them, only having partially filled the pages. The way salsa struct allocation currently works means that such pages will be "leaked" as far as allocating into them is concerned and so they won't ever be filled.
This PR implements a free list approach for the table that records unfilled pages currently not "owned" by `ZalsaLocal` instances, so that new `ZalsaLocal` instances can try fetching from that first before considering allocating a new page and putting their unfilled pages back when they drop.
> Prevent fragmention of table due to frequent `ZalsaLocal` reconstruction

- benches/compare.rs
This results in frequent allocator calling which generally hurts reliability of the benchmarks. Saw `malloc` popup as a 10% regression in https://github.com/salsa-rs/salsa/pull/717
> Don't clone strings in benchmarks

- src/database.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/zalsa.rs
- src/zalsa_local.rs
This allows reducing some dynamic dispatching calls
> Move `unwind_if_revision_cancelled` from `ZalsaLocal` to `Zalsa`

- components/salsa-macro-rules/src/setup_tracked_struct.rs
- src/tracked_struct.rs
- tests/tracked-struct-id-field-bad-hash.rs
- tests/tracked_struct_with_interned_query.rs
This PR fixes a bug specific to tracked structs that are recycled and the query doesn't read any tracked fields. 
Salsa maintains a free-list with tracked structs that were created in a previous revision but are now no longer used. The storage and IDs of those tracked structs can be reused in the next revision. This helps reduce overall memory usage and allows the recycling of IDs. 
However, the reuse of ids combined with coarse-grained dependencies as implemented today can lead to incorrect cache-reuse if a tracked struct ID gets reused and a query takes multiple arguments -- which requires interning. The problem is that the interned argument struct compares equal because the tracked struct has equal ids, making salsa believe that reusing the cached data is fine (when it isn't). 
This PR …
> Fix incorrect query caching for recycled tracked structs

- components/salsa-macro-rules/src/setup_tracked_struct.rs
- components/salsa-macros/src/salsa_struct.rs
- components/salsa-macros/src/tracked_struct.rs
- src/tracked_struct.rs
Based on https://github.com/salsa-rs/salsa/pull/708
Avoid tracking revisions for untracked fields (all tracked fields are covered by the tracked struct's `created_at` field). This should reduce memory consumption of tracked structs because it avoids tracking unused revisions for untracked field.
Closes https://github.com/salsa-rs/salsa/issues/672
> Track revisions for tracked-fields only

- .github/workflows/test.yml
miri takes ages to complete, so if one pushes frequently to their branch we now cancel the previous job with this (as its not useful anymore anyways)
> Cancel duplicate test workflow runs

- benches/accumulator.rs
- benches/compare.rs
- benches/incremental.rs
The compiler seems to throw a coin when deciding about whether to inline these or not making the codspeed profiles annoying to read
> `#[inline(never)]` queries in benchmarks

- src/function/backdate.rs
- tests/durability.rs
Noticed the test in that comment no longer existed so I had to  go digging through history to bring it back
> Add test for durability changes

- Cargo.toml
- src/function.rs
- src/function/delete.rs
- src/function/execute.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/table/memo.rs
- src/tracked_struct.rs
This PR is a rebased version of https://github.com/salsa-rs/salsa/pull/695; All credit for the changes goes to @ibraheemdev. As they put it:
> It seems that we don't actually need arc-swap for the memo table, because our `deleted_entries` queue takes care of deferring reclamation until there are no live borrows of a given memo. arc-swap does a lot of extra bookkeeping; replacing it with a manual `AtomicPtr` object speeds up red-knot's incremental performance by about 15%. This should also make it easier to test with loom/shuttle.
> 
> You'll notice that none of the safety requirements of the `MemoTable` functions actually change with this PR, so I believe it is sound. The one catch is that we have to avoid returning `ManuallyDrop<Box<T>>` and instead work with `NonNull` until the …
> internal: Replace `arc-swap` with manual `AtomicPtr`

- components/salsa-macros/src/options.rs
- src/table/memo.rs
This fixes violations of a new nightly clippy rule.
> refactor: Option::replace instead of std::mem::replace

- src/function/execute.rs
- src/function/fetch.rs
- src/function/lru.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/table/sync.rs
- src/zalsa_local.rs
Split out of https://github.com/salsa-rs/salsa/pull/743
> perf: Some small perf things

- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macros/src/db.rs
- components/salsa-macros/src/lib.rs
- src/accumulator.rs
- src/database.rs
- src/function.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/lib.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/views.rs
- src/zalsa.rs
Allows us to skip iterating over all registered view casters whenever we need to cast
> perf: Store view downcaster in function ingredients directly

- .github/workflows/test.yml
- benches/dataflow.rs
- examples/calc/type_check.rs
- src/revision.rs
- tests/cycle.rs
- tests/lru.rs
- tests/parallel/cycle_ab_peeping_c.rs
- tests/tracked_struct_disambiguates.rs
Also adjusts some numbers in tests to have miri do less repetitive work
This more than halves the runtime of our miri job, in part due to nextest itself and in part due to the number adjusting (which I noticed due nextest complaining about long >60s running tests)
> chore: Use nextest in CI

- src/active_query.rs
- src/cycle.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/input.rs
- src/interned.rs
- src/tracked_struct.rs
- src/zalsa_local.rs
The number of cycle participants is generally low so a hashset likely has more overhead compared to a simple vec for such small numbers of elements.
> perf: Use a `Vec` for `CycleHeads`

- components/salsa-macros/src/tracked_impl.rs
- tests/tracked_method.rs
The debug name of every tracked method always was `inner_fn_name`. This PR improves the function name to be `<fn_name>_`. This is not perfect but much more useful than the same name for every tracked method.
An alternative is to use `std::any::type_name` and we could then try to detect if the type name is from a `TrackedTrait` but that seems complicated.
> bug [salsa-macros]: Improve debug name of tracked methods

- book/src/plumbing/jars_and_ingredients.md
- src/accumulator.rs
- src/active_query.rs
- src/database.rs
- src/durability.rs
- src/event.rs
- src/function.rs
- src/function/accumulated.rs
- src/function/diff_outputs.rs
- src/function/execute.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/zalsa_local.rs
- tests/common/mod.rs
- tests/interned-revisions.rs
- tests/preverify-struct-with-leaked-data-2.rs
- tests/preverify-struct-with-leaked-data.rs
- tests/tracked_fn_on_input_with_high_durability.rs
Per the mentoring instructions in https://github.com/salsa-rs/salsa/issues/597.
Still needs some tests. Note this does not actually implement garbage collection but adds the necessary plumbing to do so.
> Enable Garbage Collection for Interned Values

- src/id.rs
- src/input.rs
- src/input/singleton.rs
- src/interned.rs
- src/table.rs
- src/tracked_struct.rs
- tests/tracked_with_struct_db.rs
By manually erasing the concrete slot types and dealing with the vtable ourselves
> refactor(perf): Remove extra page indirection in `Table`

- src/function.rs
- src/function/delete.rs
> Replace memo queue with append-only vector

- src/runtime.rs
- src/runtime/dependency_graph.rs
- src/table/sync.rs
Thanks to the fixpoint changes this has become obsolete actually
> refactor: Remove unnecessary query stack acess in `block_on`

- src/active_query.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/zalsa_local.rs
This saves an entire usize per function `Memo`
> refactor: Move `verified_final` from `Memo` into `QueryRevisions`

- .github/workflows/book.yml
The artifacts currently contain a `html` directory and a `linkcheck` directory with just an empty cache file, so uploading just the `html` directory will fix the book url's.
Fixes #752
> Use html directory for mdbook artifact

- components/salsa-macros/src/db.rs
- src/database_impl.rs
- src/function.rs
- src/function/delete.rs
- src/function/fetch.rs
- src/function/memo.rs
- src/interned.rs
- src/lib.rs
- src/revision.rs
- src/storage.rs
- src/table.rs
- src/table/memo.rs
- src/tracked_struct.rs
- src/update.rs
- src/views.rs
- src/zalsa.rs
Makes a start on #697, but doesn't forbid `clippy::undocumented_unsafe_blocks` yet.
Some files with many undocumented blocks allow the lint on file level for now to reduce noise.
> chore: Document most safety blocks

- src/tracked_struct.rs
Setting the field's revision to `current_revision` when updating is not technically wrong, but its pessimizing. If all previous reads only observed a change of up to `changed_at`, then it's fine for us to do the same as nothing we derive from has read from `current_revision`.
> fix: Use `changed_at` revision when updating fields

- src/cycle.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- tests/cycle_tracked.rs
Fixes https://github.com/salsa-rs/salsa/issues/785
The root cause of #785 is that Salsa tries to load the memo of a cycle head that is stored on a tracked struct that has been freed. 
The main problem is that we tried to verify `validate_provisional` even in cases where the query is from a past revision, in which case we can't trust any inputs to still exist (and be valid). 
The fix in this PR is to change the order in which `shallow_verify` and `validate_provisional` are called. This requires extracting the *mutating* bits out of `shallow_verify` because we only want to call those if the struct isn't provisional (at least, that's what we did before and I tried to preserve this behavior).
> fix: Dereferencing freed memos when verifying provisional memos

- src/function/maybe_changed_after.rs
I accidentally changed the `validate_maybe_provisional` calls to `validate_provisional` in https://github.com/salsa-rs/salsa/pull/788. This is bad for performance because it prevents Salsa from short-circuiting if the memo is already finalized.
> [fix] Use `validate_maybe_provisional` instead of `validate_provisional`

- src/event.rs
- src/function/execute.rs
- tests/common/mod.rs
- tests/cycle.rs
- tests/cycle_tracked.rs
I would like to write tests asserting about cycles iterated and log cycles iterated as a metric. Add a `WillIterateCycle` event and fire it whenever a cycle head is about to iterate the cycle again. Update some cycle tests accordingly.
> add WillIterateCycle event

- src/function/maybe_changed_after.rs
Retrieve the `QueryStack` once (including `zalsa_local`) instead of once for each cycle head
> [refactor] Reuse the same stack for all cycles heads in `validate_same_iteration`

- src/function/fetch.rs
- src/function/maybe_changed_after.rs
The basic promise of `fetch_hot` is to do the minimal amount of work for the common case and fall back to `fetch_cold` 
which repeats some of the checks for the rare cases where `fetch_hot` wasn't successful (because we failed to claim a guard, or a deep update is required).
This PR simplifies `fetch_hot` by moving the `same_iteration` check for cycle handling into `fetch_cold` (which has the advantage that `maybe_changed_after` also uses it). 
Moving the check wasn't as trivial as I hoped because it's important that we don't push the new query until after verifying if the memo is a provisional value from the same iteration. 
Codspeed reports a 2-3% perf improvement for most benchmarks.
There's a 1% perf improvement on Red Knot's incremental benchmarks …
> [refactor] Simplify `fetch_hot`

- src/active_query.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
Example output
```
dependency graph cycle when validating impl_self_ty_shim(Id(4000)), set cycle_fn/cycle_initial to fixpoint iterate.
Query stack:
[
infer_shim(Id(4400)),
trait_solve_shim(Id(6800)),
trait_impls_in_deps_shim(Id(1c00)),
trait_impls_in_crate_shim(Id(1c00)),
impl_trait_shim(Id(4000)),
impl_trait_with_diagnostics_shim(Id(4000)),
impl_self_ty_shim(Id(4000)),
impl_self_ty_with_diagnostics_shim(Id(4000)),
]
```
> Print query stack when encountering unexpected cycle

- src/active_query.rs
- src/attach.rs
- src/database.rs
- src/database_impl.rs
- src/function.rs
- src/function/accumulated.rs
- src/function/fetch.rs
- src/function/lru.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/input.rs
- src/interned.rs
- src/key.rs
- src/storage.rs
- src/tracked_struct.rs
- src/zalsa.rs
- src/zalsa_local.rs
A lot of attached calls/definitions seem to hover around the default inlining limit making the codspeed reports difficult to interpret at times, generally these should benefit from being inlined either way as the "attached" code paths are quite hot.
Aside from those, this PR touches up on a lot of other call sites for instructing inlining behavior, as just changing the attached calls has a negative impact overall on the remainder of the inlining behaviors. These additional explicit annotations bring things back in line.
> chore: Adjust `#[inline]` annotations

- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/interned.rs
Turns out the only thing that makes use of the pushed query within the scope of the push and drop of the guard in `deep_verify_memo` is `function::Ingredient::maybe_changed_after` which itself already pushes the query if it needs to. So all of this is actually unnecessary.
> perf: Don't push an unnecessary active query for `deep_verify_memo`

- src/interned.rs
- src/revision.rs
- tests/intern_access_in_different_revision.rs
There is an assert that `last_interned_at >= last_changed_revision`, and it can fail without this, see the added test.
CC @ibraheemdev, you introduced this assert in #602.
> Make interned's last_interned_at equal Revision::MAX if they are interned outside a quer

- .github/workflows/test.yml
The paths filter is incompatible with our merge group setup
> chore: Fix ci not always running

- src/id.rs
- src/interned.rs
- src/table.rs
Instead, store only an `Id`, to save memory.
This saves 65mb on rust-analyzer. Wants to see the speed impact.
> perf: Don't store the fields in the interned map

- src/function/fetch.rs
- src/function/maybe_changed_after.rs
Move the `validate_maybe_provisional` out of `fetch_hot` and only test if the memo is provisional (in which case we shouldn't mark the memo as updated). 
Rely on `fetch_cold` to lazily validate the memo. 
Codspeed thinks this is slightly better in some benchmarks (but the results change between runs). There's no meaningful change in Red Knot's benchmarks. I think it simplifies the logic a tiny bit. But I'm also okay not landing this change.
> [refactor] More `fetch_hot` simplification

- src/function.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/sync.rs
- src/input.rs
- src/interned.rs
- src/runtime.rs
- src/runtime/dependency_graph.rs
- src/table.rs
- src/table/util.rs
- src/tracked_struct.rs
- src/zalsa.rs
I believe given that the lock is held fairly shortly we ought to be fine with this coarser grained locking. A lock per ingredient to claim a sync which means we only content for the lock when two queries try to access something from the same ingredient. This reduces memory usage by a good chunk.
> refactor: Per ingredient sync table

- src/input/input_field.rs
Similar to tracked struct fields, include the struct name in the formatted index of input-fields. 
It's not clear to me how to write a test for this because the formatted index is only used in tracing logs.
> chore: Include struct name in formatted input-field index

- components/salsa-macro-rules/src/setup_accumulator_impl.rs
- components/salsa-macro-rules/src/setup_input_struct.rs
- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macros/src/db.rs
> squelch most clippy warnings in generated code

- src/function.rs
- src/function/backdate.rs
- src/function/execute.rs
- src/update.rs
cc https://github.com/salsa-rs/salsa/pull/820
unsure why this didn't fail CI anywhere. Rust is weird when it comes to lifetimes and trait functions
> fix: Fix incorrect `values_equal` signature

- components/salsa-macro-rules/src/setup_input_struct.rs
- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macro-rules/src/setup_tracked_struct.rs
- src/accumulator.rs
- src/active_query.rs
- src/durability.rs
- src/function.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/lib.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- tests/backtrace.rs
- tests/interned-structs_self_ref.rs
Example output:
```
query stacktrace:
0: query_e(Id(3)) -> (R1, Durability::LOW)
at tests/backtrace.rs:30
1: query_cycle(Id(3)) -> (R1, Durability::HIGH, iteration = 0)
at tests/backtrace.rs:43
cycle heads: query_cycle(Id(3)) -> 0
2: query_f(Id(3)) -> (R1, Durability::HIGH)
at tests/backtrace.rs:38
```
> feat: Implement a query stack `Backtrace` analog

- src/function/execute.rs
- src/runtime.rs
- src/zalsa.rs
it's gotten a bit tough to reason about imo due to the different execution modes we have now
> refactor: Clean up `function::execute`

- src/active_query.rs
- src/zalsa_local.rs
This PR fixes a panic in `Backtrace::catpure` if `local_state.query_stack` is already mutably borrowed by
returning `None`. 
This was possible because some of our cycle queries used `with_query_stack` when panicking to include the query stack
and `with_query_stack` always aquired a mutable borrow. I split `with_query_stack` into a reference, mutable reference, and `try` variant
which should avoid this from triggering in most places
> bug: Avoid panic in `Backtrace::catpure` if `query_stack` is already mutably borrowed

- components/salsa-macro-rules/src/setup_tracked_fn.rs
- tests/cycle_output.rs
- tests/preverify-struct-with-leaked-data-2.rs
The debug name `Configuration` isn't very helpful when debugging salsa. Use a name constructed from the query name.
I'm open to suggestions on how to avoid collisions with actual query names. e.g. we could prefix the name with two underscores or similar.
> better debug name for interned query arguments

- src/table/memo.rs
The `additional_len` calculation assumes that `memos.len() <= memo_ingredient_index`, which is not true in light of concurrent inserts. We're seeing spurious overflow panics because of this. It looks like this was changed in https://github.com/salsa-rs/salsa/pull/803.
> Fix memo table growth condition

- src/accumulator.rs
- src/cycle.rs
- src/function.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- tests/cycle_output.rs
Started off as investigating whether an out parameter for this would be more performant but I also believe this change makes it more easy to reason about where and how we are changing the cycle heads in verification. There is now one area where we remove from them, and 2 areas where we extend them where as before it was semi hidden due to us constructing empty cycle heads.
> Pass cycle heads as out parameter for `maybe_changed_after`

- src/function/maybe_changed_after.rs
- tests/cycle.rs
- tests/cycle_output.rs
Stacked on top of https://github.com/salsa-rs/salsa/pull/852
> Do not re-verify already verified memoized value in cycle verification 

- src/loom.rs
r-a still does not like some glob shadowing setups and fixing those is incredibly difficult with our current setup (nameres in rust is so much fun...) -> https://github.com/rust-lang/rust-analyzer/issues/19755
Without this change a big part of the code base turns red unfortunately
> Work around a rust-analyzer bug

- src/function/fetch.rs
- src/function/memo.rs
* Avoid an atomic load in the most common case where the query isn't participating in a 
cycle.
* Only perform the test in `fetch_cold` (with_retry) because memos returned by `fetch_hot` are always finalized.
> perf: speed-up cycle-retry logic

- components/salsa-macros/src/accumulator.rs
- components/salsa-macros/src/input.rs
- components/salsa-macros/src/interned.rs
- components/salsa-macros/src/options.rs
- components/salsa-macros/src/tracked_fn.rs
- components/salsa-macros/src/tracked_struct.rs
- tests/tracked_fn_orphan_escape_hatch.rs
Closes https://github.com/salsa-rs/salsa/issues/866
> Implement an `!Update` bound escape hatch for tracked fn

- src/cancelled.rs
- src/cycle.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/lib.rs
- tests/cycle.rs
- tests/cycle_initial_call_back_into_cycle.rs
Closes https://github.com/salsa-rs/salsa/issues/704
> feat: Unwind with specific type when encountering an unexpected cycle

- src/runtime.rs
Early return from `block_on` if both the current and other thread are the same to skip the need to traverse the dependency tree (which requires a lock)
> Short-circuit `block-on` if same thread

- src/id.rs
- src/input/singleton.rs
- src/key.rs
- src/table.rs
- src/tracked_struct.rs
- src/zalsa.rs
- src/zalsa_local.rs
- tests/cycle_output.rs
- tests/tracked-struct-id-field-bad-hash.rs
Pack a generation into input IDs.
The generation of a tracked struct is incremented after it is reused, allowing us to avoid read dependencies. Generational IDs were originally meant for https://github.com/salsa-rs/salsa/pull/839, as adding the necessary read dependency on interned structs that may be reused introduced a large (~50%) regression to ty's incremental performance.
This increases the size of `Id` from a `u32` to a `u64`. However, if the generation is restricted to `u16`, and ingredient indices are restricted to `u16`, this does not increase the size of `DatabaseKeyIndex`, so the memory usage effect is limited (~5% increase to ty's peak memory usage). However, this should allow us to implement garbage collection for interned values without significant performance concerns, so …
> Use generational identifiers for tracked structs

- src/active_query.rs
- src/function.rs
- src/tracked_struct.rs
- src/zalsa_local.rs
Notable we do not do this for cycles, given there the memo is likely temporary anyways
> shrink_to_fit `IdentityMap` before storing it

- src/function/fetch.rs
I often find it hard to understand the query stack when debugging salsa. 
This PR adds a `fetch` span, including the ingredient. This gives a better sense for how salsa recurses and (when enter and exit logging is enabled), when a query completes.
This is a separate PR to see how it affects perf:
Example from a recent debugging sesison of mine (the thread id part is custom)
```
2025-05-21T13:37:38.146709Z DEBUG t2{thread_id=ThreadId(4)}:fetch{query=query_c(Id(0))}:fetch{query=query_b(Id(800))}: salsa::runtime: Block ThreadId(4) on ThreadId(3) because it depends on query_a(Id(400)) (currently running on that thread).
```
> Add fetch span

- src/function/memo.rs
- tests/parallel/cycle_provisional_depending_on_itself.rs
- tests/parallel/main.rs
This fixes a hang in multithreaded fixpoint iteration where the `Memo::provisional_retry` retried over and over again because all its cycle heads other than itself were finalized at this point. 
This also fixes the panic from the `kopf` repro listed in https://github.com/salsa-rs/salsa/issues/831
> Fix hang in nested fixpoint iteration

- src/function/diff_outputs.rs
- tests/tracked-struct-id-field-bad-hash.rs
> Don't report stale outputs if there is newer generation in new_outputs

- src/function/memo.rs
This assertion failed when building for wasm
> Restrict memo size assertion to targets with 64bit pointer size

- src/active_query.rs
- src/function.rs
- src/function/accumulated.rs
- src/function/diff_outputs.rs
- src/function/inputs.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/ingredient.rs
- src/memo_ingredient_indices.rs
- src/table/memo.rs
- src/tracked_struct.rs
- src/zalsa.rs
- src/zalsa_local.rs
Packs `QueryOrigin` into a `(u64, u32, u8)` union layout to take advantage of the padding bytes in `QueryRevisions`. This cuts down the size of memos by two words.
> Pack `QueryOrigin` memory layout

- src/active_query.rs
- src/function.rs
- src/function/accumulated.rs
- src/function/backdate.rs
- src/function/diff_outputs.rs
- src/function/execute.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/zalsa_local.rs
Similar to https://github.com/salsa-rs/salsa/pull/768, except also lazily allocating the `CycleHeads`. I did some profiling in ty, and on a cold run ~1% of memos have non-empty `CycleHeads` and ~0.5% create tracked structs, out of >2M memos on large projects. Lazily allocating saves a meaningful amount of memory for us (4 words on memos without extras) and doesn't affect performance for ty (if anything it seems to improve performance very slightly, but that may just be noise).
> Lazily allocate extra memo state

- src/active_query.rs
- src/function/maybe_changed_after.rs
- src/id.rs
- src/key.rs
- src/zalsa.rs
- src/zalsa_local.rs
If we reserve a bit in `IngredientIndex` we can avoid an extra discriminator byte for each `QueryEdge` in the `input_outputs` list, which is quite meaningful.
> Pack `QueryEdge` memory layout

- src/function/execute.rs
We can set `validate_final` eagerly here instead of waiting for the next `maybe_validate_provisional`
I think this will help to mitigate some of the perf regression in my other PR
> Set `validate_final` in `execute` after removing the last cycle head

- Cargo.toml
- src/durability.rs
- src/event.rs
- src/function/memo.rs
- src/interned.rs
- src/revision.rs
- src/sync.rs
- src/tracked_struct.rs
- tests/cycle_output.rs
- tests/interned-revisions.rs
- tests/preverify-struct-with-leaked-data-2.rs
Basic implementation of https://github.com/salsa-rs/salsa/issues/597.
The garbage collection strategy used here is very simple.
- Slots that have not been accessed in the last 3 *active revisions* are always reused, and nothing else. Active revisions are those in which interned values were actually read to avoid counting empty revisions.
- Slots are never swept proactively, though this would be simple to add as an option.
- We also cannot collect low durability values, which would require `&mut db`. This could be supported with the above.
This is by no means a perfect strategy, but we can always tune it as needed once the infrastructure is in place. We may also want to expose the `N` active revisions constant as a configuration option in the `#[interned]` macro (it seems somewhat related …
> Simple LRU garbage collection for interned values

- components/salsa-macro-rules/src/setup_input_struct.rs
- src/active_query.rs
- src/input.rs
- src/input/input_field.rs
- src/lib.rs
- src/runtime.rs
- src/tracked_struct.rs
`Stamp` contains a lot of padding bytes, wasting 7 bytes per field for inputs due to the array packing. By packing each field into a separate array we regain that space
> Use `Revision` and `Durability` directly in input `Value`

- src/cycle.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/lib.rs
- tests/cycle.rs
- tests/cycle_initial_call_back_into_cycle.rs
Switch back to regular panic with string message, instead of `resume_unwind` with custom payload, for cycle panics.
This avoids having the default behavior be silent panic with no information, and allows the use of a panic hook to collect additional information, if needed.
It's not clear what the use case is for catching cycle panics specifically and treating them differently from other panics; they are not more recoverable.
Fixes https://github.com/salsa-rs/salsa/issues/891
> panic with string message again for cycle panics

- src/interned.rs
Pointed out in https://github.com/salsa-rs/salsa/pull/839#discussion_r2126459621, this reduces the size of interned values by one word (unless the fields happen to be exactly 48 bytes). I don't really like using `repr(packed)` but it seems fine in this case, the alternative makes the code a lot messier.
> reduce size of interned value metadata

- src/interned.rs
- tests/interned-revisions.rs
As pointed out in https://github.com/salsa-rs/salsa/issues/904#issuecomment-2957128163, we have to remove values from the LRU if their durability increases.
> Remove high-durability values from interned LRU

- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macros/src/accumulator.rs
- components/salsa-macros/src/input.rs
- components/salsa-macros/src/interned.rs
- components/salsa-macros/src/options.rs
- components/salsa-macros/src/salsa_struct.rs
- components/salsa-macros/src/tracked_fn.rs
- components/salsa-macros/src/tracked_struct.rs
- src/interned.rs
- tests/compile-fail/accumulator_incompatibles.rs
- tests/compile-fail/accumulator_incompatibles.stderr
- tests/compile-fail/input_struct_incompatibles.rs
- tests/compile-fail/input_struct_incompatibles.stderr
- tests/compile-fail/interned_struct_incompatibles.rs
- tests/compile-fail/tracked_fn_incompatibles.rs
- tests/compile-fail/tracked_fn_incompatibles.stderr
- tests/compile-fail/tracked_impl_incompatibles.rs
- tests/compile-fail/tracked_impl_incompatibles.stderr
- tests/compile-fail/tracked_struct_incompatibles.rs
- tests/compile-fail/tracked_struct_incompatibles.stderr
- tests/interned-revisions.rs
Adds the ability to tune and disable interned value garbage collection via an attribute:
```rust
#[salsa::interned(revisions = <1 | 2 | ... | usize::MAX>)]
struct Interned<'db>;
```
`revisions` is the minimum number of active revisions that must pass before a stale value is considered for garbage collection. Note that an *active revision* is one in which an instance of the interned struct has been read, so consecutive writes that create new revisions in sequence do not invalidate all interned values. Currently this constant is hard-coded to 3 internally for no good reason. Setting it to `usize::MAX` will disable garbage collection altogether (cc @Veykril).
I'm torn on whether to hard-code `usize::MAX` as the immortal value or to make that more explicit, e.g. `salsa::interned(durability = …
> Add an option to tune interned garbage collection

- src/accumulator/accumulated_map.rs
- src/cycle.rs
- src/database.rs
- src/function/memo.rs
- src/ingredient.rs
- src/input.rs
- src/interned.rs
- src/lib.rs
- src/table.rs
- src/table/memo.rs
- src/tracked_struct.rs
- src/zalsa.rs
- src/zalsa_local.rs
- tests/memory-usage.rs
This PR adds the methods `<dyn Database>::{structs_info, queries_info}`, which allow accessing memory usage information about salsa structs and memos. In ty, this lets us generate a report that looks like this:
```
=======SALSA DUMP=======
`Definition`                                       metadata=7.21MB   fields=14.41MB  count=180134
`Expression`                                       metadata=4.42MB   fields=4.42MB   count=92086
`member_lookup_with_policy_::interned_arguments`   metadata=1.94MB   fields=2.21MB   count=34566
`class_member_with_policy_::interned_arguments`    metadata=1.56MB   fields=1.78MB   count=27820
`IntersectionType`                                 metadata=0.75MB   fields=1.50MB   count=13350
`OverloadLiteral`                                  metadata=1.19MB …
```
> Add API to dump memory usage

- CHANGELOG.md
- components/salsa-macro-rules/src/setup_tracked_fn.rs
Salsa also supports tracked methods and tracked associated methods, neither of which produce equivalent user-observable structs, so arguably neither should track functions, and the generated structs don't really provide a usable API anyway.
> Hide generated structs of tracked functions from docs via `#[doc(hidden)]`

- src/table.rs
The codegen for this function is pretty terrible currently because of all the debug machinery.
> Optimize page access

- components/salsa-macro-rules/src/setup_accumulator_impl.rs
- components/salsa-macro-rules/src/setup_input_struct.rs
- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macro-rules/src/setup_tracked_struct.rs
- src/ingredient.rs
- src/ingredient_cache.rs
- src/tracked_struct.rs
- src/zalsa.rs
- src/zalsa_local.rs
- tests/interned-structs_self_ref.rs
@Veykril might need to verify my logic here, but I think this is correct given either the `inventory` feature or the nonce checks, as `IngredientCache` always loads the index directly from the database.
The safety arguments for unchecked access are less clear for other uses of `lookup_ingredient`. The most notable one is in `DatabaseKeyIndex::maybe_changed_after`, where I think it's actually possible that a function records a dependency on an ingredient from a different database, in which case we should panic. It would be nice if we could guarantee that ingredient indices are stable even with manual registration, but that sort of defeats the purpose.
> Remove bounds and type checks from `IngredientCache`

- src/database_impl.rs
- src/function/backdate.rs
- src/function/execute.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/function/specify.rs
- src/lib.rs
- src/runtime.rs
- src/tracing.rs
- src/tracked_struct.rs
- src/zalsa.rs
- src/zalsa_local.rs
It doesn't make sense for these to be inlined as they're typically disabled anyways.
> Outline all tracing events

- src/input.rs
- src/interned.rs
- src/table/memo.rs
- src/tracked_struct.rs
This is just a small optimization that takes advantage of the fact that an index being valid for a `MemoTable` guarantees that it is valid for the corresponding `MemoTableTypes`, so we can avoid the duplicate bounds checks here.
It would be nice if we could remove the bounds and type checks here completely, but I don't think that's possible because we sometimes compute the `MemoIngredientIndex` from a salsa supertype `Id`, which could be smuggled across databases.
> Remove extra bounds checks from memo table hot-paths

- components/salsa-macro-rules/src/setup_input_struct.rs
- components/salsa-macro-rules/src/setup_interned_struct.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- components/salsa-macro-rules/src/setup_tracked_struct.rs
- components/salsa-macros/src/db.rs
- src/accumulator.rs
- src/database.rs
- src/function.rs
- src/function/accumulated.rs
- src/function/execute.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/lib.rs
- src/parallel.rs
- src/storage.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
- src/views.rs
- src/zalsa.rs
- tests/debug_db_contents.rs
- tests/interned-structs.rs
- tests/interned-structs_self_ref.rs
This removes occurences of `dyn Database` internally where only the zalsas are needed for (hopefully) a perf increase.
Lastly it renames downcasting to upcasting, because thats what we are doing, `dyn Database` --downcast-> `Concrete` --upcast-->`dyn CustomDatabaseTrait`
> Do manual trait casting

- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/memo.rs
- src/zalsa_local.rs
Curious to see the performance impact.
> Remove borrow checks from `ZalsaLocal`

- .github/workflows/test.yml
- Cargo.toml
- components/salsa-macro-rules/Cargo.toml
- components/salsa-macro-rules/src/gate_accumulated.rs
- components/salsa-macro-rules/src/lib.rs
- components/salsa-macro-rules/src/setup_tracked_fn.rs
- src/active_query.rs
- src/function.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/function/specify.rs
- src/ingredient.rs
- src/lib.rs
- src/zalsa_local.rs
- tests/accumulate-chain.rs
- tests/accumulate-custom-debug.rs
- tests/accumulate-dag.rs
- tests/accumulate-execution-order.rs
- tests/accumulate-from-tracked-fn.rs
- tests/accumulate-no-duplicates.rs
- tests/accumulate-reuse-workaround.rs
- tests/accumulate-reuse.rs
- tests/accumulate.rs
- tests/accumulated_backdate.rs
- tests/cycle_accumulate.rs
Mainly wanna see if this has a perf impact, but the other rational is that rust-analyzer simply does not use this feature (and from past discussions we don't really see how we could use it given it defeats incrementality).
> Gate accumulator feature behind a feature flag

- src/accumulator.rs
- src/cycle.rs
- src/function.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/ingredient.rs
- src/input.rs
- src/input/input_field.rs
- src/interned.rs
- src/key.rs
- src/tracked_struct.rs
- src/tracked_struct/tracked_field.rs
I'm debugging a run-away issue with fixpoint iteration and cycle heads and
was confused why it is okay to push `IterationCount::initial` in `maybe_changed_after` if
The memo we're verifying is from a later iteration. 
It turns out, this is fine because the `iteration_count` is never used in `maybe_update_after`. 
This PR introduces a `CycleHeadKeys` that only tracks the heads without iteration 
to clarify that the iteration is irrelevant in this part of the code.
> refactor: Use `CycleHeadKeys` in `maybe_changed_after`

- src/database.rs
We (ty) use the salsa database to enforce exclusive ownership 
of `Arc`s. These may or may not be stored in the salsa database (we'll do a regular `set_input` if they're stored in the db).
The way this is implemented is that we call `as_dyn_database_mut().zalsa_mut()` 
before unwrapping the `Arc`. This allows us to avoid copying potentially large data structures.
However, https://github.com/salsa-rs/salsa/commit/211bc158dfe432138cfa77c6e0a51b6a2bc82884#r163337827 removed
`as_dyn_database_mut`. 
Ideally, Salsa would have a dedicated feature for Arcs like this. For now, I suggest
Adding a method that triggers cancellation without bumping the revision.
Previous discussion https://salsa.zulipchat.com/#narrow/stream/333573-salsa-3.2E0/topic/Expose.20an.20API.20to.20cancel.20other.20queries
> Expose API to manually trigger cancellation

- src/database.rs
- tests/memory-usage.rs
Moves all the memory usage information into a single method. This avoid calling the `heap_size` methods multiple times for user structs, to make external profiling easier.
> Consolidate memory usage information API

- src/id.rs
- src/key.rs
This improves codegen, but not sure it'll have a measurable impact:
```diff
- hash_one_id:
- 	mov eax, dword ptr [rdi]
- 	mov ecx, dword ptr [rdi + 4]
- 	movabs rdx, -1065810590584100411
- 	imul rax, rdx
- 	add rax, rcx
- 	imul rax, rdx
- 	rol rax, 26
-   ret
+ hash_one_id:
+ 	movabs rax, -1065810590584100411
+ 	imul rax, qword ptr [rdi]
+ 	rol rax, 26
+   ret
```
> Optimize `Id::hash`

- .github/workflows/test.yml
- src/function/execute.rs
- src/function/fetch.rs
- src/function/maybe_changed_after.rs
- src/zalsa_local.rs
Splitting this out of https://github.com/salsa-rs/salsa/pull/995 to get a better sense for what's causing the perf regression. 
https://github.com/salsa-rs/salsa/pull/995 needs to control the `iteration_count` (there are cases where it doesn't start from 0). That's why pushing the new query needs to be moved into `execute_maybe_iterate` (and `execute` for non cyclic queries)
> refactor: Push active query in execute
